"""Type definitions for reasoning artifacts returned by the Honcho API.

These TypedDict definitions provide IDE autocomplete and type checking for
reasoning artifacts (hypotheses, predictions, traces, inductions) returned
from API queries.

Example:
    ```python
    from honcho import Honcho
    from honcho.reasoning_types import Hypothesis, Induction

    client = Honcho()
    peer = client.peer("user-123")

    # Type hints provide autocomplete
    hypotheses: list[Hypothesis] = peer.get_hypotheses(status="active")
    for hyp in hypotheses:
        print(hyp["content"])  # IDE knows this key exists
        print(hyp["confidence_score"])  # Autocomplete available
    ```
"""

from typing import Any, TypedDict


class Hypothesis(TypedDict, total=False):
    """A hypothesis generated by the Abducer agent during reasoning dreams.

    Hypotheses are explanatory theories about observed patterns. They evolve
    over time through the prediction-falsification cycle.

    Attributes:
        id: Unique identifier for this hypothesis
        workspace_name: Workspace this hypothesis belongs to
        observer: Peer ID who made the observations
        observed: Peer ID being observed
        content: The hypothesis statement explaining observed patterns
        confidence_score: Confidence level (0.0-1.0)
        tier: Confidence tier (1=exploratory, 2=working, 3=candidate)
        status: Current status (active, superseded, falsified)
        source_premise_ids: List of observation IDs that support this hypothesis
        reasoning_metadata: Additional metadata about hypothesis generation
        created_at: When this hypothesis was created
        updated_at: When this hypothesis was last updated
    """

    id: str
    workspace_name: str
    observer: str
    observed: str
    content: str
    confidence_score: float
    tier: int
    status: str
    source_premise_ids: list[str]
    reasoning_metadata: dict[str, Any]
    created_at: str
    updated_at: str


class Prediction(TypedDict, total=False):
    """A testable prediction derived from a hypothesis.

    Predictions are generated by the Predictor agent and tested by the
    Falsifier agent through contradiction search.

    Attributes:
        id: Unique identifier for this prediction
        workspace_name: Workspace this prediction belongs to
        hypothesis_id: ID of the parent hypothesis
        content: The prediction statement (testable claim)
        status: Current status (untested, unfalsified, falsified, superseded)
        is_blind: Whether this prediction was made without looking at future data
        embedding: Vector embedding for semantic search (may be None)
        created_at: When this prediction was created
        updated_at: When this prediction was last updated
    """

    id: str
    workspace_name: str
    hypothesis_id: str
    content: str
    status: str
    is_blind: bool
    embedding: list[float] | None
    created_at: str
    updated_at: str


class FalsificationTrace(TypedDict, total=False):
    """A record of the falsification process for a prediction.

    Traces are immutable records created by the Falsifier agent documenting
    the search for contradictions to a prediction.

    Attributes:
        id: Unique identifier for this trace
        workspace_name: Workspace this trace belongs to
        prediction_id: ID of the prediction being tested
        search_queries: List of search queries used to find contradictions
        contradicting_premise_ids: IDs of observations that contradict the prediction
        reasoning_chain: Step-by-step reasoning process
        final_status: Result of falsification (unfalsified, falsified, untested)
        search_count: Number of search iterations performed
        search_efficiency_score: How efficiently contradictions were found (0.0-1.0)
        created_at: When this trace was created
    """

    id: str
    workspace_name: str
    prediction_id: str
    search_queries: list[str]
    contradicting_premise_ids: list[str]
    reasoning_chain: str
    final_status: str
    search_count: int
    search_efficiency_score: float
    created_at: str


class Induction(TypedDict, total=False):
    """A stable pattern extracted from unfalsified predictions.

    Inductions are general patterns discovered by the Inductor agent from
    predictions that survived the falsification process.

    Attributes:
        id: Unique identifier for this induction
        workspace_name: Workspace this induction belongs to
        observer: Peer ID who observed the pattern
        observed: Peer ID being observed
        content: The pattern statement (generalized insight)
        pattern_type: Type of pattern (preferential, behavioral, personality, tendency)
        confidence: Confidence level (low, medium, high)
        source_prediction_ids: IDs of predictions that formed this pattern
        source_premise_ids: IDs of observations that support this pattern
        stability_score: How stable this pattern is (0.0-1.0)
        created_at: When this induction was created
        updated_at: When this induction was last updated
    """

    id: str
    workspace_name: str
    observer: str
    observed: str
    content: str
    pattern_type: str
    confidence: str
    source_prediction_ids: list[str]
    source_premise_ids: list[str]
    stability_score: float
    created_at: str
    updated_at: str


class HypothesisGenealogy(TypedDict):
    """The evolution tree for a hypothesis showing parent/child relationships.

    Attributes:
        hypothesis: The current hypothesis
        parents: List of parent hypotheses this superseded
        children: List of child hypotheses that superseded this one
        reasoning_metadata: Metadata explaining the evolution
    """

    hypothesis: Hypothesis
    parents: list[Hypothesis]
    children: list[Hypothesis]
    reasoning_metadata: dict[str, Any]


class InductionSources(TypedDict):
    """The source predictions and observations that formed an induction.

    Attributes:
        induction: The induction pattern
        predictions: List of predictions that formed this pattern
        premises: List of observations that support the predictions
    """

    induction: Induction
    predictions: list[Prediction]
    premises: list[dict[str, Any]]  # Document type
