-- Honcho schema, ported from the Python Alembic migrations.
-- Generated by snapshotting `alembic upgrade head` (25 migrations) with
-- pg_dump --schema-only, then making it schema-relative so the objects are
-- created in the connection's search_path (set from DB_SCHEMA by the app).
-- Regenerate via the procedure in api-rs/migrations/README.md.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE active_queue_sessions (
    last_updated timestamp with time zone DEFAULT now() NOT NULL,
    id text NOT NULL,
    work_unit_key text NOT NULL
);

CREATE TABLE collections (
    id text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    workspace_name text NOT NULL,
    internal_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    observer text NOT NULL,
    observed text NOT NULL,
    CONSTRAINT ck_collections_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_collections_id_length CHECK ((length(id) = 21)),
    CONSTRAINT ck_collections_public_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_collections_public_id_length CHECK ((length(id) = 21))
);

CREATE TABLE documents (
    id text NOT NULL,
    internal_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    content text NOT NULL,
    embedding vector(1536),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    workspace_name text NOT NULL,
    session_name text,
    observer text NOT NULL,
    observed text NOT NULL,
    level text DEFAULT 'explicit'::text NOT NULL,
    times_derived integer DEFAULT 1 NOT NULL,
    source_ids jsonb,
    deleted_at timestamp with time zone,
    sync_state text DEFAULT 'pending'::text NOT NULL,
    last_sync_at timestamp with time zone,
    sync_attempts integer DEFAULT 0 NOT NULL,
    CONSTRAINT ck_documents_content_length CHECK ((length(content) <= 65535)),
    CONSTRAINT ck_documents_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_documents_id_length CHECK ((length(id) = 21)),
    CONSTRAINT ck_documents_public_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_documents_public_id_length CHECK ((length(id) = 21))
);

CREATE TABLE message_embeddings (
    id bigint NOT NULL,
    content text NOT NULL,
    embedding vector(1536),
    message_id text NOT NULL,
    workspace_name text NOT NULL,
    session_name text NOT NULL,
    peer_name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    sync_state text DEFAULT 'pending'::text NOT NULL,
    last_sync_at timestamp with time zone,
    sync_attempts integer DEFAULT 0 NOT NULL
);

ALTER TABLE message_embeddings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME message_embeddings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE messages (
    id bigint NOT NULL,
    public_id text NOT NULL,
    content text NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    peer_name text NOT NULL,
    workspace_name text NOT NULL,
    session_name text NOT NULL,
    token_count integer DEFAULT 0 NOT NULL,
    internal_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    seq_in_session bigint NOT NULL,
    CONSTRAINT ck_messages_content_length CHECK ((length(content) <= 65535)),
    CONSTRAINT ck_messages_public_id_format CHECK ((public_id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_messages_public_id_length CHECK ((length(public_id) = 21))
);

ALTER TABLE messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE peers (
    id text NOT NULL,
    name text NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    configuration jsonb DEFAULT '{}'::jsonb NOT NULL,
    internal_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    workspace_name text NOT NULL,
    CONSTRAINT ck_peers_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_peers_id_length CHECK ((length(id) = 21)),
    CONSTRAINT ck_users_name_length CHECK ((length(name) <= 512)),
    CONSTRAINT ck_users_public_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_users_public_id_length CHECK ((length(id) = 21))
);

CREATE TABLE queue (
    id bigint NOT NULL,
    session_id text,
    payload jsonb NOT NULL,
    processed boolean DEFAULT false NOT NULL,
    task_type text NOT NULL,
    work_unit_key text NOT NULL,
    error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    workspace_name text,
    message_id bigint
);

ALTER TABLE queue ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME queue_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE session_peers (
    workspace_name text NOT NULL,
    session_name text NOT NULL,
    peer_name text NOT NULL,
    configuration jsonb DEFAULT '{}'::jsonb NOT NULL,
    internal_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    joined_at timestamp with time zone DEFAULT now() NOT NULL,
    left_at timestamp with time zone
);

CREATE TABLE sessions (
    id text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    configuration jsonb DEFAULT '{}'::jsonb NOT NULL,
    internal_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    workspace_name text NOT NULL,
    name text NOT NULL,
    CONSTRAINT ck_sessions_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_sessions_id_length CHECK ((length(id) = 21)),
    CONSTRAINT ck_sessions_name_length CHECK ((length(name) <= 512)),
    CONSTRAINT ck_sessions_public_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_sessions_public_id_length CHECK ((length(id) = 21))
);

CREATE TABLE webhook_endpoints (
    id text NOT NULL,
    workspace_name text NOT NULL,
    url text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_webhook_endpoints_webhook_endpoint_url_length CHECK ((length(url) <= 2048))
);

CREATE TABLE workspaces (
    id text NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    configuration jsonb DEFAULT '{}'::jsonb NOT NULL,
    internal_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT ck_apps_name_length CHECK ((length(name) <= 512)),
    CONSTRAINT ck_apps_public_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_apps_public_id_length CHECK ((length(id) = 21)),
    CONSTRAINT ck_workspaces_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_workspaces_id_length CHECK ((length(id) = 21))
);

ALTER TABLE ONLY active_queue_sessions
    ADD CONSTRAINT pk_active_queue_sessions PRIMARY KEY (id);

ALTER TABLE ONLY collections
    ADD CONSTRAINT pk_collections PRIMARY KEY (id);

ALTER TABLE ONLY documents
    ADD CONSTRAINT pk_documents PRIMARY KEY (id);

ALTER TABLE ONLY message_embeddings
    ADD CONSTRAINT pk_message_embeddings PRIMARY KEY (id);

ALTER TABLE ONLY messages
    ADD CONSTRAINT pk_messages PRIMARY KEY (id);

ALTER TABLE ONLY peers
    ADD CONSTRAINT pk_peers PRIMARY KEY (id);

ALTER TABLE ONLY queue
    ADD CONSTRAINT pk_queue PRIMARY KEY (id);

ALTER TABLE ONLY session_peers
    ADD CONSTRAINT pk_session_peers PRIMARY KEY (workspace_name, session_name, peer_name);

ALTER TABLE ONLY sessions
    ADD CONSTRAINT pk_sessions PRIMARY KEY (id);

ALTER TABLE ONLY webhook_endpoints
    ADD CONSTRAINT pk_webhook_endpoints PRIMARY KEY (id);

ALTER TABLE ONLY workspaces
    ADD CONSTRAINT pk_workspaces PRIMARY KEY (id);

ALTER TABLE ONLY active_queue_sessions
    ADD CONSTRAINT uq_active_queue_sessions_work_unit_key UNIQUE (work_unit_key);

ALTER TABLE ONLY collections
    ADD CONSTRAINT uq_collections_observer_observed_workspace_name UNIQUE (observer, observed, workspace_name);

ALTER TABLE ONLY messages
    ADD CONSTRAINT uq_messages_public_id UNIQUE (public_id);

ALTER TABLE ONLY messages
    ADD CONSTRAINT uq_messages_workspace_name_session_name_seq_in_session UNIQUE (workspace_name, session_name, seq_in_session);

ALTER TABLE ONLY peers
    ADD CONSTRAINT uq_peers_name_workspace_name UNIQUE (name, workspace_name);

ALTER TABLE ONLY sessions
    ADD CONSTRAINT uq_sessions_name_workspace_name UNIQUE (name, workspace_name);

ALTER TABLE ONLY workspaces
    ADD CONSTRAINT uq_workspaces_name UNIQUE (name);

CREATE INDEX ix_collections_created_at ON collections USING btree (created_at);

CREATE INDEX ix_collections_observed ON collections USING btree (observed);

CREATE INDEX ix_collections_observer ON collections USING btree (observer);

CREATE INDEX ix_collections_workspace_name ON collections USING btree (workspace_name);

CREATE INDEX ix_documents_created_at ON documents USING btree (created_at);

CREATE INDEX ix_documents_deleted_at ON documents USING btree (deleted_at) WHERE (deleted_at IS NOT NULL);

CREATE INDEX ix_documents_embedding_hnsw ON documents USING hnsw (embedding vector_cosine_ops) WITH (m='16', ef_construction='64');

CREATE INDEX ix_documents_observed ON documents USING btree (observed);

CREATE INDEX ix_documents_observer ON documents USING btree (observer);

CREATE INDEX ix_documents_session_name ON documents USING btree (session_name);

CREATE INDEX ix_documents_source_ids_gin ON documents USING gin (source_ids);

CREATE INDEX ix_documents_sync_state ON documents USING btree (sync_state);

CREATE INDEX ix_documents_sync_state_last_sync_at ON documents USING btree (sync_state, last_sync_at);

CREATE INDEX ix_documents_workspace_name ON documents USING btree (workspace_name);

CREATE INDEX ix_message_embeddings_created_at ON message_embeddings USING btree (created_at);

CREATE INDEX ix_message_embeddings_embedding_hnsw ON message_embeddings USING hnsw (embedding vector_cosine_ops) WITH (m='16', ef_construction='64');

CREATE INDEX ix_message_embeddings_message_id ON message_embeddings USING btree (message_id);

CREATE INDEX ix_message_embeddings_peer_name ON message_embeddings USING btree (peer_name);

CREATE INDEX ix_message_embeddings_session_name ON message_embeddings USING btree (session_name);

CREATE INDEX ix_message_embeddings_sync_state ON message_embeddings USING btree (sync_state);

CREATE INDEX ix_message_embeddings_sync_state_last_sync_at ON message_embeddings USING btree (sync_state, last_sync_at);

CREATE INDEX ix_message_embeddings_workspace_name ON message_embeddings USING btree (workspace_name);

CREATE INDEX ix_messages_content_gin ON messages USING gin (to_tsvector('english'::regconfig, content));

CREATE INDEX ix_messages_created_at ON messages USING btree (created_at);

CREATE INDEX ix_messages_peer_name ON messages USING btree (peer_name);

CREATE INDEX ix_messages_session_lookup ON messages USING btree (session_name, id) INCLUDE (id, created_at);

CREATE INDEX ix_messages_workspace_name ON messages USING btree (workspace_name);

CREATE INDEX ix_peers_created_at ON peers USING btree (created_at);

CREATE INDEX ix_peers_workspace_name ON peers USING btree (workspace_name);

CREATE INDEX ix_queue_created_at ON queue USING btree (created_at);

CREATE INDEX ix_queue_message_id_not_null ON queue USING btree (message_id) WHERE (message_id IS NOT NULL);

CREATE INDEX ix_queue_processed ON queue USING btree (processed);

CREATE INDEX ix_queue_session_id ON queue USING btree (session_id);

CREATE INDEX ix_queue_work_unit_key_processed_id ON queue USING btree (work_unit_key, processed, id);

CREATE INDEX ix_queue_workspace_name ON queue USING btree (workspace_name);

CREATE INDEX ix_sessions_created_at ON sessions USING btree (created_at);

CREATE INDEX ix_sessions_workspace_name ON sessions USING btree (workspace_name);

CREATE INDEX ix_webhook_endpoints_workspace_name ON webhook_endpoints USING btree (workspace_name);

CREATE INDEX ix_workspaces_created_at ON workspaces USING btree (created_at);

CREATE UNIQUE INDEX uq_queue_dream_pending_work_unit_key ON queue USING btree (work_unit_key) WHERE ((task_type = 'dream'::text) AND (processed = false));

CREATE UNIQUE INDEX uq_queue_reconciler_pending_work_unit_key ON queue USING btree (work_unit_key) WHERE ((task_type = 'reconciler'::text) AND (processed = false));

ALTER TABLE ONLY collections
    ADD CONSTRAINT fk_collections_observed_workspace_name_peers FOREIGN KEY (observed, workspace_name) REFERENCES peers(name, workspace_name);

ALTER TABLE ONLY collections
    ADD CONSTRAINT fk_collections_observer_workspace_name_peers FOREIGN KEY (observer, workspace_name) REFERENCES peers(name, workspace_name);

ALTER TABLE ONLY collections
    ADD CONSTRAINT fk_collections_workspace_name_workspaces FOREIGN KEY (workspace_name) REFERENCES workspaces(name);

ALTER TABLE ONLY documents
    ADD CONSTRAINT fk_documents_observed_workspace_name_peers FOREIGN KEY (observed, workspace_name) REFERENCES peers(name, workspace_name);

ALTER TABLE ONLY documents
    ADD CONSTRAINT fk_documents_observer_observed_workspace_name_collections FOREIGN KEY (observer, observed, workspace_name) REFERENCES collections(observer, observed, workspace_name);

ALTER TABLE ONLY documents
    ADD CONSTRAINT fk_documents_observer_workspace_name_peers FOREIGN KEY (observer, workspace_name) REFERENCES peers(name, workspace_name);

ALTER TABLE ONLY documents
    ADD CONSTRAINT fk_documents_session_workspace FOREIGN KEY (session_name, workspace_name) REFERENCES sessions(name, workspace_name);

ALTER TABLE ONLY documents
    ADD CONSTRAINT fk_documents_workspace_name_workspaces FOREIGN KEY (workspace_name) REFERENCES workspaces(name);

ALTER TABLE ONLY message_embeddings
    ADD CONSTRAINT fk_message_embeddings_message_id_messages FOREIGN KEY (message_id) REFERENCES messages(public_id) ON DELETE CASCADE;

ALTER TABLE ONLY message_embeddings
    ADD CONSTRAINT fk_message_embeddings_peer_name_workspace_name_peers FOREIGN KEY (peer_name, workspace_name) REFERENCES peers(name, workspace_name);

ALTER TABLE ONLY message_embeddings
    ADD CONSTRAINT fk_message_embeddings_session_name_workspace_name_sessions FOREIGN KEY (session_name, workspace_name) REFERENCES sessions(name, workspace_name);

ALTER TABLE ONLY message_embeddings
    ADD CONSTRAINT fk_message_embeddings_workspace_name_workspaces FOREIGN KEY (workspace_name) REFERENCES workspaces(name);

ALTER TABLE ONLY messages
    ADD CONSTRAINT fk_messages_peer_name_peers FOREIGN KEY (peer_name, workspace_name) REFERENCES peers(name, workspace_name);

ALTER TABLE ONLY messages
    ADD CONSTRAINT fk_messages_session_name_sessions FOREIGN KEY (session_name, workspace_name) REFERENCES sessions(name, workspace_name);

ALTER TABLE ONLY peers
    ADD CONSTRAINT fk_peers_workspace_name_workspaces FOREIGN KEY (workspace_name) REFERENCES workspaces(name);

ALTER TABLE ONLY queue
    ADD CONSTRAINT fk_queue_message_id FOREIGN KEY (message_id) REFERENCES messages(id);

ALTER TABLE ONLY queue
    ADD CONSTRAINT fk_queue_session_id FOREIGN KEY (session_id) REFERENCES sessions(id);

ALTER TABLE ONLY queue
    ADD CONSTRAINT fk_queue_workspace_name FOREIGN KEY (workspace_name) REFERENCES workspaces(name);

ALTER TABLE ONLY session_peers
    ADD CONSTRAINT fk_session_peers_peer_name_workspace_name_peers FOREIGN KEY (peer_name, workspace_name) REFERENCES peers(name, workspace_name);

ALTER TABLE ONLY session_peers
    ADD CONSTRAINT fk_session_peers_session_name_workspace_name_sessions FOREIGN KEY (session_name, workspace_name) REFERENCES sessions(name, workspace_name);

ALTER TABLE ONLY session_peers
    ADD CONSTRAINT fk_session_peers_workspace_name FOREIGN KEY (workspace_name) REFERENCES workspaces(name);

ALTER TABLE ONLY sessions
    ADD CONSTRAINT fk_sessions_workspace_name_workspaces FOREIGN KEY (workspace_name) REFERENCES workspaces(name);

ALTER TABLE ONLY webhook_endpoints
    ADD CONSTRAINT fk_webhook_endpoints_workspace_name_workspaces FOREIGN KEY (workspace_name) REFERENCES workspaces(name);
