"""Render Compose + ``.env`` for a local stack profile."""

from __future__ import annotations

import os
from contextlib import suppress
from importlib.resources import files
from pathlib import Path

from honcho_cli.local.profile import LocalProfile

# Keys honcho start owns. Unknown lines in an existing .env are preserved.
MANAGED_KEYS = (
    "AUTH_USE_AUTH",
    "LOG_LEVEL",
    "LLM_OPENAI_API_KEY",
    "HONCHO_IMAGE",
    "API_PORT",
    "DB_PORT",
    "REDIS_PORT",
)

_HEADER = (
    "# Generated by honcho start. Extra keys below the managed block are preserved."
)

_PLACEHOLDERS = frozenset(
    {
        "",
        "your-api-key-here",
        "changeme",
        "sk-...",
    }
)


def is_placeholder_key(value: str | None) -> bool:
    """True when ``value`` is missing or a known template placeholder."""
    if value is None:
        return True
    return value.strip() in _PLACEHOLDERS


def read_env_value(path: Path, key: str) -> str | None:
    """Return the raw value for ``key`` in a dotenv file, or None."""
    if not path.exists():
        return None
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError:
        return None
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        k, _, v = stripped.partition("=")
        if k.strip() == key:
            return _unquote(v.strip())
    return None


def managed_env(profile: LocalProfile, llm_api_key: str) -> dict[str, str]:
    """Values written into the managed block of ``.env``."""
    return {
        "AUTH_USE_AUTH": "false",
        "LOG_LEVEL": "INFO",
        "LLM_OPENAI_API_KEY": llm_api_key,
        "HONCHO_IMAGE": profile.image,
        "API_PORT": str(profile.api_port),
        "DB_PORT": str(profile.db_port),
        "REDIS_PORT": str(profile.redis_port),
    }


def upsert_env(path: Path, updates: dict[str, str]) -> None:
    """Write managed keys, preserving unrelated user lines.

    Drops a previous generated header so it is not duplicated.
    """
    extras: list[str] = []
    if path.exists():
        for line in path.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            if stripped == _HEADER or stripped.startswith(
                "# Generated by honcho start"
            ):
                continue
            if not stripped or stripped.startswith("#"):
                extras.append(line)
                continue
            if "=" in stripped:
                k, _, _ = stripped.partition("=")
                if k.strip() in updates or k.strip() in MANAGED_KEYS:
                    continue
            extras.append(line)

    managed = [f"{k}={updates[k]}" for k in MANAGED_KEYS if k in updates]
    body = [_HEADER, *managed]
    if extras:
        # Keep a blank line between managed and user keys when there are extras.
        if extras[0].strip():
            body.append("")
        body.extend(extras)
    path.write_text("\n".join(body) + "\n")
    with suppress(OSError):
        os.chmod(path, 0o600)


def render_stack(profile: LocalProfile, llm_api_key: str) -> None:
    """Write compose, init.sql, and .env into the profile directory."""
    directory = profile.dir()
    directory.mkdir(parents=True, exist_ok=True)
    with suppress(OSError):
        os.chmod(directory, 0o700)

    templates = files("honcho_cli.local.templates")
    compose = templates.joinpath("docker-compose.yml").read_text(encoding="utf-8")
    init_sql = templates.joinpath("init.sql").read_text(encoding="utf-8")
    profile.compose_file().write_text(compose)
    (directory / "init.sql").write_text(init_sql)
    upsert_env(profile.env_file(), managed_env(profile, llm_api_key))


def _unquote(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        return value[1:-1]
    return value
