"""Local-stack contracts: profile files, env merge, image pin, port remap."""

from __future__ import annotations

import json
import os
import subprocess

import pytest
from honcho_cli.local.docker import (
    DockerError,
    allocate_host_ports,
    compose_up,
    pin_image,
    seed_config_toml,
)
from honcho_cli.local.env import managed_env, read_env_value, render_stack, upsert_env
from honcho_cli.local.profile import LocalProfile, load_profile, save_profile


@pytest.fixture
def cfg_dir(tmp_path, monkeypatch):
    monkeypatch.setattr("honcho_cli.config.CONFIG_DIR", tmp_path)
    monkeypatch.setattr("honcho_cli.config.CONFIG_FILE", tmp_path / "config.json")
    for k in [k for k in os.environ if k.startswith("HONCHO_")]:
        monkeypatch.delenv(k)
    return tmp_path


def test_profile_roundtrip_has_no_secrets(cfg_dir):
    profile = LocalProfile(
        name="local",
        api_port=8001,
        image="ghcr.io/plastic-labs/honcho@sha256:abc",
    )
    save_profile(profile)
    loaded = load_profile("local")
    assert loaded.api_port == 8001
    assert loaded.image.endswith("@sha256:abc")
    on_disk = json.loads(profile.profile_file().read_text())
    assert "LLM" not in json.dumps(on_disk)
    assert set(on_disk) == {"inference", "apiPort", "dbPort", "redisPort", "image"}


def test_upsert_preserves_extra_env_keys(tmp_path):
    path = tmp_path / ".env"
    path.write_text("LLM_OPENAI_API_KEY=old\nCUSTOM_FLAG=keep-me\n# user comment\n")
    upsert_env(path, managed_env(LocalProfile(name="local"), "sk-new"))
    text = path.read_text()
    assert "LLM_OPENAI_API_KEY=sk-new" in text
    assert "CUSTOM_FLAG=keep-me" in text
    assert "user comment" in text
    assert text.count("Generated by honcho start") == 1


def test_render_stack_uses_published_image(cfg_dir):
    profile = LocalProfile(name="local")
    render_stack(profile, "sk-test")
    compose = profile.compose_file().read_text()
    assert "ghcr.io/plastic-labs/honcho" in compose
    assert "build:" not in compose
    assert compose.count("./config.toml:/app/config.toml:ro") == 2
    assert read_env_value(profile.env_file(), "AUTH_USE_AUTH") == "false"
    assert oct(profile.env_file().stat().st_mode)[-3:] == "600"


def test_pin_latest_to_matching_digest(monkeypatch):
    pulls: list[str] = []

    def fake_run(args, *, check=False):
        if args[:1] == ["pull"]:
            pulls.append(args[1])
            return subprocess.CompletedProcess(args, 0, stdout="", stderr="")
        if args[:2] == ["image", "inspect"]:
            body = json.dumps(
                [
                    "ghcr.io/plastic-labs/honcho@sha256:deadbeef",
                    "ghcr.io/other/honcho@sha256:nope",
                ]
            )
            return subprocess.CompletedProcess(args, 0, stdout=body, stderr="")
        raise AssertionError(args)

    monkeypatch.setattr("honcho_cli.local.docker._run_docker", fake_run)
    assert pin_image("ghcr.io/plastic-labs/honcho:latest") == (
        "ghcr.io/plastic-labs/honcho@sha256:deadbeef"
    )
    assert pulls == ["ghcr.io/plastic-labs/honcho:latest"]


def test_seed_config_toml_writes_once(cfg_dir, monkeypatch):
    profile = LocalProfile(
        name="local", image="ghcr.io/plastic-labs/honcho@sha256:abc"
    )
    monkeypatch.setattr(
        "honcho_cli.local.docker._copy_from_image",
        lambda image, paths: "[deriver]\nWORKERS = 2\n",
    )
    assert seed_config_toml(profile) is True
    profile.config_file().write_text(
        profile.config_file().read_text() + "# user edit\n"
    )
    assert seed_config_toml(profile) is False
    assert "# user edit" in profile.config_file().read_text()


def test_busy_port_remaps_unless_pinned(monkeypatch):
    monkeypatch.setattr(
        "honcho_cli.local.docker.port_available",
        lambda port, host="127.0.0.1": port != 6379,
    )
    profile, remapped = allocate_host_ports(LocalProfile(name="local"))
    assert profile.redis_port == 6380
    assert remapped["redis"] == (6379, 6380)

    with pytest.raises(DockerError) as exc:
        allocate_host_ports(LocalProfile(name="local"), pinned=frozenset({"redis"}))
    assert exc.value.code == "PORT_IN_USE"
    assert exc.value.details["flag"] == "--redis-port"


def test_compose_up_retries_without_creds_store(monkeypatch, tmp_path):
    cfg = tmp_path / "config.json"
    cfg.write_text(json.dumps({"credsStore": "desktop"}))
    monkeypatch.setattr("honcho_cli.local.docker._docker_user_config", lambda: cfg)
    fail = subprocess.CompletedProcess(
        args=["docker", "compose", "up", "-d"],
        returncode=1,
        stdout="",
        stderr=(
            'error getting credentials - err: exec: "docker-credential-desktop": '
            "executable file not found in $PATH, out: ``\n"
        ),
    )
    ok = subprocess.CompletedProcess(
        args=["docker", "compose", "up", "-d"],
        returncode=0,
        stdout="",
        stderr="",
    )
    calls: list[dict | None] = []

    def fake_run(profile, args, *, capture=False, check=True, extra_env=None):
        calls.append(extra_env)
        return fail if extra_env is None else ok

    monkeypatch.setattr("honcho_cli.local.docker._run_compose", fake_run)
    compose_up(LocalProfile(name="local"))
    assert [c is None for c in calls] == [True, False]
    assert "DOCKER_CONFIG" in calls[1]
