"""Generate ``docs/snippets/cli-commands.mdx`` from the Typer app.

Walks the ``honcho`` Typer app and emits a Mintlify snippet describing every
command, argument, and option. The output is a single snippet intended to be
included by ``docs/v3/documentation/reference/cli.mdx`` via ``<Snippet>``.

Usage::

    uv run --package honcho-cli python honcho-cli/scripts/generate_cli_docs.py

    # Or as a drift check (non-zero exit if the committed snippet is stale):
    uv run --package honcho-cli python honcho-cli/scripts/generate_cli_docs.py --check
"""

from __future__ import annotations

import sys
from argparse import ArgumentParser
from pathlib import Path

import click
import typer.main

from honcho_cli.main import app

REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT = REPO_ROOT / "docs" / "snippets" / "cli-commands.mdx"

HEADER = """{/*
  GENERATED by honcho-cli/scripts/generate_cli_docs.py — do not edit.
  Re-generate with: uv run --package honcho-cli python honcho-cli/scripts/generate_cli_docs.py
  Source of truth: honcho-cli/src/honcho_cli/commands/
*/}

"""


def _escape_mdx(text: str) -> str:
    """Escape MDX-sensitive characters in prose so Mintlify's parser doesn't
    mistake ``{...}`` for a JSX expression or ``<x>`` for a JSX tag."""
    return (
        text.replace("\\", "\\\\")
        .replace("{", "\\{")
        .replace("}", "\\}")
        .replace("<", "\\<")
    )


def _format_param(param: click.Parameter) -> str:
    if isinstance(param, click.Argument):
        name = param.name or ""
        return f"`<{name}>`" + ("" if param.required else " (optional)")
    opts = " / ".join(f"`{o}`" for o in param.opts)
    if param.secondary_opts:
        opts += " / " + " / ".join(f"`{o}`" for o in param.secondary_opts)
    if isinstance(param, click.Option) and param.help:
        return f"{opts} — {_escape_mdx(param.help)}"
    return opts


def _render(cmd: click.Command, path: list[str]) -> list[str]:
    lines: list[str] = []
    full = " ".join(path)
    if len(path) <= 2:
        lines.append(f"## {full}\n")
    else:
        lines.append(f"**{full}**\n")
    if cmd.help:
        lines.append(f"{_escape_mdx(cmd.help.strip())}\n")

    args = [p for p in cmd.params if isinstance(p, click.Argument)]
    opts = [p for p in cmd.params if isinstance(p, click.Option) and not p.hidden]

    if args:
        lines.append("**Arguments**\n")
        for p in args:
            lines.append(f"- {_format_param(p)}")
        lines.append("")

    if opts:
        lines.append("**Options**\n")
        for p in opts:
            lines.append(f"- {_format_param(p)}")
        lines.append("")

    if isinstance(cmd, click.Group):
        for sub_name in sorted(cmd.commands):
            lines.extend(_render(cmd.commands[sub_name], path + [sub_name]))
    return lines


def build() -> str:
    root: click.Command = typer.main.get_command(app)
    if not isinstance(root, click.Group):
        raise SystemExit("Expected root command to be a Group")

    body: list[str] = []
    for name in sorted(root.commands):
        body.extend(_render(root.commands[name], ["honcho", name]))
    return HEADER + "\n".join(body) + "\n"


def main() -> int:
    parser = ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the committed snippet differs from generated output.",
    )
    ns = parser.parse_args()
    generated = build()
    if ns.check:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != generated:
            print(
                f"::error::{OUTPUT} is stale. Re-run without --check to regenerate.",
                file=sys.stderr,
            )
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated)
    print(f"Wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
