[tool.poetry]
name = "api2"
version = "0.1.0"
description = ""
authors = ["hyusap <paulayush@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.105.0"
uvicorn = "^0.24.0.post1"
langchain = "^0.0.350"
openai = "^1.3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
