--
-- PostgreSQL database dump
--


-- Dumped from database version 15.18 (Debian 15.18-1.pgdg12+1)
-- Dumped by pg_dump version 15.18 (Debian 15.18-1.pgdg12+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: active_queue_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.active_queue_sessions (
    last_updated timestamp with time zone DEFAULT now() NOT NULL,
    id text NOT NULL,
    work_unit_key text NOT NULL
);


--
-- Name: alembic_version; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.alembic_version (
    version_num character varying(32) NOT NULL
);


--
-- Name: collections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.collections (
    id text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    workspace_name text NOT NULL,
    internal_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    observer text NOT NULL,
    observed text NOT NULL,
    CONSTRAINT ck_collections_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_collections_id_length CHECK ((length(id) = 21)),
    CONSTRAINT ck_collections_public_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_collections_public_id_length CHECK ((length(id) = 21))
);


--
-- Name: documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documents (
    id text NOT NULL,
    internal_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    content text NOT NULL,
    embedding public.vector(1536),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    workspace_name text NOT NULL,
    session_name text,
    observer text NOT NULL,
    observed text NOT NULL,
    level text DEFAULT 'explicit'::text NOT NULL,
    times_derived integer DEFAULT 1 NOT NULL,
    source_ids jsonb,
    deleted_at timestamp with time zone,
    sync_state text DEFAULT 'pending'::text NOT NULL,
    last_sync_at timestamp with time zone,
    sync_attempts integer DEFAULT 0 NOT NULL,
    CONSTRAINT ck_documents_content_length CHECK ((length(content) <= 65535)),
    CONSTRAINT ck_documents_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_documents_id_length CHECK ((length(id) = 21)),
    CONSTRAINT ck_documents_public_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_documents_public_id_length CHECK ((length(id) = 21))
);


--
-- Name: message_embeddings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.message_embeddings (
    id bigint NOT NULL,
    content text NOT NULL,
    embedding public.vector(1536),
    message_id text NOT NULL,
    workspace_name text NOT NULL,
    session_name text NOT NULL,
    peer_name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    sync_state text DEFAULT 'pending'::text NOT NULL,
    last_sync_at timestamp with time zone,
    sync_attempts integer DEFAULT 0 NOT NULL
);


--
-- Name: message_embeddings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.message_embeddings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.message_embeddings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.messages (
    id bigint NOT NULL,
    public_id text NOT NULL,
    content text NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    peer_name text NOT NULL,
    workspace_name text NOT NULL,
    session_name text NOT NULL,
    token_count integer DEFAULT 0 NOT NULL,
    internal_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    seq_in_session bigint NOT NULL,
    CONSTRAINT ck_messages_content_length CHECK ((length(content) <= 65535)),
    CONSTRAINT ck_messages_public_id_format CHECK ((public_id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_messages_public_id_length CHECK ((length(public_id) = 21))
);


--
-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: peers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.peers (
    id text NOT NULL,
    name text NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    configuration jsonb DEFAULT '{}'::jsonb NOT NULL,
    internal_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    workspace_name text NOT NULL,
    CONSTRAINT ck_peers_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_peers_id_length CHECK ((length(id) = 21)),
    CONSTRAINT ck_users_name_length CHECK ((length(name) <= 512)),
    CONSTRAINT ck_users_public_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_users_public_id_length CHECK ((length(id) = 21))
);


--
-- Name: queue; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.queue (
    id bigint NOT NULL,
    session_id text,
    payload jsonb NOT NULL,
    processed boolean DEFAULT false NOT NULL,
    task_type text NOT NULL,
    work_unit_key text NOT NULL,
    error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    workspace_name text,
    message_id bigint
);


--
-- Name: queue_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.queue ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.queue_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: session_peers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.session_peers (
    workspace_name text NOT NULL,
    session_name text NOT NULL,
    peer_name text NOT NULL,
    configuration jsonb DEFAULT '{}'::jsonb NOT NULL,
    internal_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    joined_at timestamp with time zone DEFAULT now() NOT NULL,
    left_at timestamp with time zone
);


--
-- Name: sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sessions (
    id text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    configuration jsonb DEFAULT '{}'::jsonb NOT NULL,
    internal_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    workspace_name text NOT NULL,
    name text NOT NULL,
    CONSTRAINT ck_sessions_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_sessions_id_length CHECK ((length(id) = 21)),
    CONSTRAINT ck_sessions_name_length CHECK ((length(name) <= 512)),
    CONSTRAINT ck_sessions_public_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_sessions_public_id_length CHECK ((length(id) = 21))
);


--
-- Name: webhook_endpoints; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.webhook_endpoints (
    id text NOT NULL,
    workspace_name text NOT NULL,
    url text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_webhook_endpoints_webhook_endpoint_url_length CHECK ((length(url) <= 2048))
);


--
-- Name: workspaces; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workspaces (
    id text NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    configuration jsonb DEFAULT '{}'::jsonb NOT NULL,
    internal_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT ck_apps_name_length CHECK ((length(name) <= 512)),
    CONSTRAINT ck_apps_public_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_apps_public_id_length CHECK ((length(id) = 21)),
    CONSTRAINT ck_workspaces_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_workspaces_id_length CHECK ((length(id) = 21))
);


--
-- Name: alembic_version alembic_version_pkc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alembic_version
    ADD CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num);


--
-- Name: active_queue_sessions pk_active_queue_sessions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.active_queue_sessions
    ADD CONSTRAINT pk_active_queue_sessions PRIMARY KEY (id);


--
-- Name: collections pk_collections; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collections
    ADD CONSTRAINT pk_collections PRIMARY KEY (id);


--
-- Name: documents pk_documents; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT pk_documents PRIMARY KEY (id);


--
-- Name: message_embeddings pk_message_embeddings; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_embeddings
    ADD CONSTRAINT pk_message_embeddings PRIMARY KEY (id);


--
-- Name: messages pk_messages; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT pk_messages PRIMARY KEY (id);


--
-- Name: peers pk_peers; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.peers
    ADD CONSTRAINT pk_peers PRIMARY KEY (id);


--
-- Name: queue pk_queue; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.queue
    ADD CONSTRAINT pk_queue PRIMARY KEY (id);


--
-- Name: session_peers pk_session_peers; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_peers
    ADD CONSTRAINT pk_session_peers PRIMARY KEY (workspace_name, session_name, peer_name);


--
-- Name: sessions pk_sessions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT pk_sessions PRIMARY KEY (id);


--
-- Name: webhook_endpoints pk_webhook_endpoints; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.webhook_endpoints
    ADD CONSTRAINT pk_webhook_endpoints PRIMARY KEY (id);


--
-- Name: workspaces pk_workspaces; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspaces
    ADD CONSTRAINT pk_workspaces PRIMARY KEY (id);


--
-- Name: active_queue_sessions uq_active_queue_sessions_work_unit_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.active_queue_sessions
    ADD CONSTRAINT uq_active_queue_sessions_work_unit_key UNIQUE (work_unit_key);


--
-- Name: collections uq_collections_observer_observed_workspace_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collections
    ADD CONSTRAINT uq_collections_observer_observed_workspace_name UNIQUE (observer, observed, workspace_name);


--
-- Name: messages uq_messages_public_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT uq_messages_public_id UNIQUE (public_id);


--
-- Name: messages uq_messages_workspace_name_session_name_seq_in_session; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT uq_messages_workspace_name_session_name_seq_in_session UNIQUE (workspace_name, session_name, seq_in_session);


--
-- Name: peers uq_peers_name_workspace_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.peers
    ADD CONSTRAINT uq_peers_name_workspace_name UNIQUE (name, workspace_name);


--
-- Name: sessions uq_sessions_name_workspace_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT uq_sessions_name_workspace_name UNIQUE (name, workspace_name);


--
-- Name: workspaces uq_workspaces_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspaces
    ADD CONSTRAINT uq_workspaces_name UNIQUE (name);


--
-- Name: ix_collections_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_collections_created_at ON public.collections USING btree (created_at);


--
-- Name: ix_collections_observed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_collections_observed ON public.collections USING btree (observed);


--
-- Name: ix_collections_observer; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_collections_observer ON public.collections USING btree (observer);


--
-- Name: ix_collections_workspace_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_collections_workspace_name ON public.collections USING btree (workspace_name);


--
-- Name: ix_documents_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_documents_created_at ON public.documents USING btree (created_at);


--
-- Name: ix_documents_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_documents_deleted_at ON public.documents USING btree (deleted_at) WHERE (deleted_at IS NOT NULL);


--
-- Name: ix_documents_embedding_hnsw; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_documents_embedding_hnsw ON public.documents USING hnsw (embedding public.vector_cosine_ops) WITH (m='16', ef_construction='64');


--
-- Name: ix_documents_observed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_documents_observed ON public.documents USING btree (observed);


--
-- Name: ix_documents_observer; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_documents_observer ON public.documents USING btree (observer);


--
-- Name: ix_documents_session_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_documents_session_name ON public.documents USING btree (session_name);


--
-- Name: ix_documents_source_ids_gin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_documents_source_ids_gin ON public.documents USING gin (source_ids);


--
-- Name: ix_documents_sync_state; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_documents_sync_state ON public.documents USING btree (sync_state);


--
-- Name: ix_documents_sync_state_last_sync_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_documents_sync_state_last_sync_at ON public.documents USING btree (sync_state, last_sync_at);


--
-- Name: ix_documents_workspace_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_documents_workspace_name ON public.documents USING btree (workspace_name);


--
-- Name: ix_message_embeddings_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_message_embeddings_created_at ON public.message_embeddings USING btree (created_at);


--
-- Name: ix_message_embeddings_embedding_hnsw; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_message_embeddings_embedding_hnsw ON public.message_embeddings USING hnsw (embedding public.vector_cosine_ops) WITH (m='16', ef_construction='64');


--
-- Name: ix_message_embeddings_message_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_message_embeddings_message_id ON public.message_embeddings USING btree (message_id);


--
-- Name: ix_message_embeddings_peer_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_message_embeddings_peer_name ON public.message_embeddings USING btree (peer_name);


--
-- Name: ix_message_embeddings_session_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_message_embeddings_session_name ON public.message_embeddings USING btree (session_name);


--
-- Name: ix_message_embeddings_sync_state; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_message_embeddings_sync_state ON public.message_embeddings USING btree (sync_state);


--
-- Name: ix_message_embeddings_sync_state_last_sync_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_message_embeddings_sync_state_last_sync_at ON public.message_embeddings USING btree (sync_state, last_sync_at);


--
-- Name: ix_message_embeddings_workspace_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_message_embeddings_workspace_name ON public.message_embeddings USING btree (workspace_name);


--
-- Name: ix_messages_content_gin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_messages_content_gin ON public.messages USING gin (to_tsvector('english'::regconfig, content));


--
-- Name: ix_messages_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_messages_created_at ON public.messages USING btree (created_at);


--
-- Name: ix_messages_peer_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_messages_peer_name ON public.messages USING btree (peer_name);


--
-- Name: ix_messages_session_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_messages_session_lookup ON public.messages USING btree (session_name, id) INCLUDE (id, created_at);


--
-- Name: ix_messages_workspace_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_messages_workspace_name ON public.messages USING btree (workspace_name);


--
-- Name: ix_peers_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_peers_created_at ON public.peers USING btree (created_at);


--
-- Name: ix_peers_workspace_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_peers_workspace_name ON public.peers USING btree (workspace_name);


--
-- Name: ix_queue_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_queue_created_at ON public.queue USING btree (created_at);


--
-- Name: ix_queue_message_id_not_null; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_queue_message_id_not_null ON public.queue USING btree (message_id) WHERE (message_id IS NOT NULL);


--
-- Name: ix_queue_processed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_queue_processed ON public.queue USING btree (processed);


--
-- Name: ix_queue_session_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_queue_session_id ON public.queue USING btree (session_id);


--
-- Name: ix_queue_work_unit_key_processed_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_queue_work_unit_key_processed_id ON public.queue USING btree (work_unit_key, processed, id);


--
-- Name: ix_queue_workspace_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_queue_workspace_name ON public.queue USING btree (workspace_name);


--
-- Name: ix_sessions_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sessions_created_at ON public.sessions USING btree (created_at);


--
-- Name: ix_sessions_workspace_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sessions_workspace_name ON public.sessions USING btree (workspace_name);


--
-- Name: ix_webhook_endpoints_workspace_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_webhook_endpoints_workspace_name ON public.webhook_endpoints USING btree (workspace_name);


--
-- Name: ix_workspaces_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_workspaces_created_at ON public.workspaces USING btree (created_at);


--
-- Name: uq_queue_dream_pending_work_unit_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_queue_dream_pending_work_unit_key ON public.queue USING btree (work_unit_key) WHERE ((task_type = 'dream'::text) AND (processed = false));


--
-- Name: uq_queue_reconciler_pending_work_unit_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_queue_reconciler_pending_work_unit_key ON public.queue USING btree (work_unit_key) WHERE ((task_type = 'reconciler'::text) AND (processed = false));


--
-- Name: collections fk_collections_observed_workspace_name_peers; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collections
    ADD CONSTRAINT fk_collections_observed_workspace_name_peers FOREIGN KEY (observed, workspace_name) REFERENCES public.peers(name, workspace_name);


--
-- Name: collections fk_collections_observer_workspace_name_peers; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collections
    ADD CONSTRAINT fk_collections_observer_workspace_name_peers FOREIGN KEY (observer, workspace_name) REFERENCES public.peers(name, workspace_name);


--
-- Name: collections fk_collections_workspace_name_workspaces; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collections
    ADD CONSTRAINT fk_collections_workspace_name_workspaces FOREIGN KEY (workspace_name) REFERENCES public.workspaces(name);


--
-- Name: documents fk_documents_observed_workspace_name_peers; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT fk_documents_observed_workspace_name_peers FOREIGN KEY (observed, workspace_name) REFERENCES public.peers(name, workspace_name);


--
-- Name: documents fk_documents_observer_observed_workspace_name_collections; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT fk_documents_observer_observed_workspace_name_collections FOREIGN KEY (observer, observed, workspace_name) REFERENCES public.collections(observer, observed, workspace_name);


--
-- Name: documents fk_documents_observer_workspace_name_peers; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT fk_documents_observer_workspace_name_peers FOREIGN KEY (observer, workspace_name) REFERENCES public.peers(name, workspace_name);


--
-- Name: documents fk_documents_session_workspace; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT fk_documents_session_workspace FOREIGN KEY (session_name, workspace_name) REFERENCES public.sessions(name, workspace_name);


--
-- Name: documents fk_documents_workspace_name_workspaces; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT fk_documents_workspace_name_workspaces FOREIGN KEY (workspace_name) REFERENCES public.workspaces(name);


--
-- Name: message_embeddings fk_message_embeddings_message_id_messages; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_embeddings
    ADD CONSTRAINT fk_message_embeddings_message_id_messages FOREIGN KEY (message_id) REFERENCES public.messages(public_id) ON DELETE CASCADE;


--
-- Name: message_embeddings fk_message_embeddings_peer_name_workspace_name_peers; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_embeddings
    ADD CONSTRAINT fk_message_embeddings_peer_name_workspace_name_peers FOREIGN KEY (peer_name, workspace_name) REFERENCES public.peers(name, workspace_name);


--
-- Name: message_embeddings fk_message_embeddings_session_name_workspace_name_sessions; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_embeddings
    ADD CONSTRAINT fk_message_embeddings_session_name_workspace_name_sessions FOREIGN KEY (session_name, workspace_name) REFERENCES public.sessions(name, workspace_name);


--
-- Name: message_embeddings fk_message_embeddings_workspace_name_workspaces; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_embeddings
    ADD CONSTRAINT fk_message_embeddings_workspace_name_workspaces FOREIGN KEY (workspace_name) REFERENCES public.workspaces(name);


--
-- Name: messages fk_messages_peer_name_peers; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fk_messages_peer_name_peers FOREIGN KEY (peer_name, workspace_name) REFERENCES public.peers(name, workspace_name);


--
-- Name: messages fk_messages_session_name_sessions; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fk_messages_session_name_sessions FOREIGN KEY (session_name, workspace_name) REFERENCES public.sessions(name, workspace_name);


--
-- Name: peers fk_peers_workspace_name_workspaces; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.peers
    ADD CONSTRAINT fk_peers_workspace_name_workspaces FOREIGN KEY (workspace_name) REFERENCES public.workspaces(name);


--
-- Name: queue fk_queue_message_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.queue
    ADD CONSTRAINT fk_queue_message_id FOREIGN KEY (message_id) REFERENCES public.messages(id);


--
-- Name: queue fk_queue_session_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.queue
    ADD CONSTRAINT fk_queue_session_id FOREIGN KEY (session_id) REFERENCES public.sessions(id);


--
-- Name: queue fk_queue_workspace_name; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.queue
    ADD CONSTRAINT fk_queue_workspace_name FOREIGN KEY (workspace_name) REFERENCES public.workspaces(name);


--
-- Name: session_peers fk_session_peers_peer_name_workspace_name_peers; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_peers
    ADD CONSTRAINT fk_session_peers_peer_name_workspace_name_peers FOREIGN KEY (peer_name, workspace_name) REFERENCES public.peers(name, workspace_name);


--
-- Name: session_peers fk_session_peers_session_name_workspace_name_sessions; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_peers
    ADD CONSTRAINT fk_session_peers_session_name_workspace_name_sessions FOREIGN KEY (session_name, workspace_name) REFERENCES public.sessions(name, workspace_name);


--
-- Name: session_peers fk_session_peers_workspace_name; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_peers
    ADD CONSTRAINT fk_session_peers_workspace_name FOREIGN KEY (workspace_name) REFERENCES public.workspaces(name);


--
-- Name: sessions fk_sessions_workspace_name_workspaces; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT fk_sessions_workspace_name_workspaces FOREIGN KEY (workspace_name) REFERENCES public.workspaces(name);


--
-- Name: webhook_endpoints fk_webhook_endpoints_workspace_name_workspaces; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.webhook_endpoints
    ADD CONSTRAINT fk_webhook_endpoints_workspace_name_workspaces FOREIGN KEY (workspace_name) REFERENCES public.workspaces(name);


--
-- PostgreSQL database dump complete
--


