"""add graph memory tables (edges, access_log, context_index, thread_binding_registry)

Revision ID: 2a3b4c5d6e7f
Revises: b765d82110bd
Create Date: 2026-06-23 17:45:00.000000

"""
from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB
from alembic import op

revision: str = "2a3b4c5d6e7f"
down_revision: str | None = "b765d82110bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    
    # --- edges table ---
    op.create_table(
        "edges",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column("workspace_name", sa.Text(), nullable=False),
        sa.Column("collection_name", sa.Text(), nullable=False),
        sa.Column("source_obs_id", sa.Text(), nullable=False),
        sa.Column("target_obs_id", sa.Text(), nullable=False),
        sa.Column("edge_type", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("metadata", sa.JSONB(), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.ForeignKeyConstraint(["source_obs_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_obs_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_name"], ["workspaces.name"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_name", "collection_name", "source_obs_id", "target_obs_id", "edge_type", name="uq_edge"),
        sa.CheckConstraint("source_obs_id != target_obs_id", name="ck_edge_different_obs"),
    )
    op.create_index("ix_edges_source", "edges", ["workspace_name", "collection_name", "source_obs_id"])
    op.create_index("ix_edges_target", "edges", ["workspace_name", "collection_name", "target_obs_id"])
    op.create_index("ix_edges_type", "edges", ["workspace_name", "collection_name", "edge_type"])
    op.create_index("ix_edges_created_by", "edges", ["workspace_name", "created_by"])
    
    # --- access_log table ---
    op.create_table(
        "access_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column("workspace_name", sa.Text(), nullable=False),
        sa.Column("collection_name", sa.Text(), nullable=False),
        sa.Column("obs_id", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Text(), nullable=False),
        sa.Column("session_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["obs_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_access_log_obs", "access_log", ["workspace_name", "collection_name", "obs_id", "created_at"])
    op.create_index("ix_access_log_created_by", "access_log", ["workspace_name", "collection_name", "created_by"])
    
    # --- context_index table ---
    op.create_table(
        "context_index",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column("workspace_name", sa.Text(), nullable=False),
        sa.Column("context_name", sa.Text(), nullable=False),
        sa.Column("obs_id", sa.Text(), nullable=False),
        sa.Column("thread_id", sa.Text(), nullable=True),
        sa.Column("added_by", sa.Text(), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["obs_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_name"], ["workspaces.name"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_name", "context_name", "obs_id", name="uq_context_member"),
    )
    op.create_index("ix_context_name", "context_index", ["workspace_name", "context_name"])
    op.create_index("ix_context_thread", "context_index", ["workspace_name", "thread_id"])
    
    # --- thread_binding_registry table ---
    op.create_table(
        "thread_binding_registry",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column("workspace_name", sa.Text(), nullable=False),
        sa.Column("thread_id", sa.Text(), nullable=False),
        sa.Column("context_name", sa.Text(), nullable=False),
        sa.Column("bound_by", sa.Text(), nullable=False),
        sa.Column("bound_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["workspace_name"], ["workspaces.name"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_name", "thread_id", name="uq_thread_binding"),
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_table("thread_binding_registry")
    op.drop_table("context_index")
    op.drop_table("access_log")
    op.drop_table("edges")
    # ### end Alembic commands ###
