"""add_phase_1_top_down_models

Revision ID: 2efcb031e5e7
Revises: 7c0d9a4e3b1f
Create Date: 2026-01-17 00:18:46.629617

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector
from migrations.utils import get_schema

# revision identifiers, used by Alembic.
revision: str = '2efcb031e5e7'
down_revision: str | None = '7c0d9a4e3b1f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

schema = get_schema()

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hypotheses',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), server_default='active', nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0.5'), nullable=False),
    sa.Column('source_premise_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('NULL'), nullable=True),
    sa.Column('unaccounted_premises_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('search_coverage', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('tier', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('reasoning_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('observer', sa.TEXT(), nullable=False),
    sa.Column('observed', sa.TEXT(), nullable=False),
    sa.Column('workspace_name', sa.TEXT(), nullable=False),
    sa.Column('collection_id', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id ~ '^[A-Za-z0-9_-]+$'", name=op.f('ck_hypotheses_hypothesis_id_format')),
    sa.CheckConstraint("status IN ('active', 'superseded', 'falsified')", name=op.f('ck_hypotheses_hypothesis_status_valid')),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name=op.f('ck_hypotheses_hypothesis_confidence_range')),
    sa.CheckConstraint('length(content) <= 65535', name=op.f('ck_hypotheses_hypothesis_content_length')),
    sa.CheckConstraint('length(id) = 21', name=op.f('ck_hypotheses_hypothesis_id_length')),
    sa.ForeignKeyConstraint(['observed', 'workspace_name'], ['public.peers.name', 'public.peers.workspace_name'], name=op.f('fk_hypotheses_observed_workspace_name_peers')),
    sa.ForeignKeyConstraint(['observer', 'observed', 'workspace_name'], ['public.collections.observer', 'public.collections.observed', 'public.collections.workspace_name'], name=op.f('fk_hypotheses_observer_observed_workspace_name_collections')),
    sa.ForeignKeyConstraint(['observer', 'workspace_name'], ['public.peers.name', 'public.peers.workspace_name'], name=op.f('fk_hypotheses_observer_workspace_name_peers')),
    sa.ForeignKeyConstraint(['workspace_name'], ['public.workspaces.name'], name=op.f('fk_hypotheses_workspace_name_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hypotheses')),
    schema='public'
    )
    op.create_index(op.f('ix_hypotheses_collection_id'), 'hypotheses', ['collection_id'], unique=False, schema='public')
    op.create_index(op.f('ix_hypotheses_created_at'), 'hypotheses', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('ix_hypotheses_observed'), 'hypotheses', ['observed'], unique=False, schema='public')
    op.create_index(op.f('ix_hypotheses_observer'), 'hypotheses', ['observer'], unique=False, schema='public')
    op.create_index('ix_hypotheses_source_premise_ids_gin', 'hypotheses', ['source_premise_ids'], unique=False, schema='public', postgresql_using='gin')
    op.create_index(op.f('ix_hypotheses_status'), 'hypotheses', ['status'], unique=False, schema='public')
    op.create_index(op.f('ix_hypotheses_workspace_name'), 'hypotheses', ['workspace_name'], unique=False, schema='public')
    op.create_table('inductions',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('source_prediction_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('NULL'), nullable=True),
    sa.Column('source_premise_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('NULL'), nullable=True),
    sa.Column('pattern_type', sa.TEXT(), nullable=False),
    sa.Column('confidence', sa.TEXT(), server_default='medium', nullable=False),
    sa.Column('stability_score', sa.Float(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('observer', sa.TEXT(), nullable=False),
    sa.Column('observed', sa.TEXT(), nullable=False),
    sa.Column('workspace_name', sa.TEXT(), nullable=False),
    sa.Column('collection_id', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confidence IN ('high', 'medium', 'low')", name=op.f('ck_inductions_induction_confidence_valid')),
    sa.CheckConstraint("id ~ '^[A-Za-z0-9_-]+$'", name=op.f('ck_inductions_induction_id_format')),
    sa.CheckConstraint("pattern_type IN ('temporal', 'causal', 'correlational', 'structural')", name=op.f('ck_inductions_induction_pattern_type_valid')),
    sa.CheckConstraint('length(content) <= 65535', name=op.f('ck_inductions_induction_content_length')),
    sa.CheckConstraint('length(id) = 21', name=op.f('ck_inductions_induction_id_length')),
    sa.CheckConstraint('stability_score >= 0.0 AND stability_score <= 1.0 OR stability_score IS NULL', name=op.f('ck_inductions_induction_stability_range')),
    sa.ForeignKeyConstraint(['observed', 'workspace_name'], ['public.peers.name', 'public.peers.workspace_name'], name=op.f('fk_inductions_observed_workspace_name_peers')),
    sa.ForeignKeyConstraint(['observer', 'observed', 'workspace_name'], ['public.collections.observer', 'public.collections.observed', 'public.collections.workspace_name'], name=op.f('fk_inductions_observer_observed_workspace_name_collections')),
    sa.ForeignKeyConstraint(['observer', 'workspace_name'], ['public.peers.name', 'public.peers.workspace_name'], name=op.f('fk_inductions_observer_workspace_name_peers')),
    sa.ForeignKeyConstraint(['workspace_name'], ['public.workspaces.name'], name=op.f('fk_inductions_workspace_name_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inductions')),
    schema='public'
    )
    op.create_index(op.f('ix_inductions_collection_id'), 'inductions', ['collection_id'], unique=False, schema='public')
    op.create_index(op.f('ix_inductions_confidence'), 'inductions', ['confidence'], unique=False, schema='public')
    op.create_index(op.f('ix_inductions_created_at'), 'inductions', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('ix_inductions_observed'), 'inductions', ['observed'], unique=False, schema='public')
    op.create_index(op.f('ix_inductions_observer'), 'inductions', ['observer'], unique=False, schema='public')
    op.create_index(op.f('ix_inductions_pattern_type'), 'inductions', ['pattern_type'], unique=False, schema='public')
    op.create_index('ix_inductions_source_prediction_ids_gin', 'inductions', ['source_prediction_ids'], unique=False, schema='public', postgresql_using='gin')
    op.create_index('ix_inductions_source_premise_ids_gin', 'inductions', ['source_premise_ids'], unique=False, schema='public', postgresql_using='gin')
    op.create_index(op.f('ix_inductions_workspace_name'), 'inductions', ['workspace_name'], unique=False, schema='public')
    op.create_table('predictions',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), server_default='untested', nullable=False),
    sa.Column('hypothesis_id', sa.TEXT(), nullable=False),
    sa.Column('source_hypothesis_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('NULL'), nullable=True),
    sa.Column('is_blind', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('workspace_name', sa.TEXT(), nullable=False),
    sa.Column('collection_id', sa.TEXT(), nullable=True),
    sa.Column('embedding', Vector(1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id ~ '^[A-Za-z0-9_-]+$'", name=op.f('ck_predictions_prediction_id_format')),
    sa.CheckConstraint("status IN ('unfalsified', 'falsified', 'untested')", name=op.f('ck_predictions_prediction_status_valid')),
    sa.CheckConstraint('length(content) <= 65535', name=op.f('ck_predictions_prediction_content_length')),
    sa.CheckConstraint('length(id) = 21', name=op.f('ck_predictions_prediction_id_length')),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['public.hypotheses.id'], name=op.f('fk_predictions_hypothesis_id_hypotheses')),
    sa.ForeignKeyConstraint(['workspace_name'], ['public.workspaces.name'], name=op.f('fk_predictions_workspace_name_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions')),
    schema='public'
    )
    op.create_index(op.f('ix_predictions_collection_id'), 'predictions', ['collection_id'], unique=False, schema='public')
    op.create_index(op.f('ix_predictions_created_at'), 'predictions', ['created_at'], unique=False, schema='public')
    op.create_index('ix_predictions_embedding_hnsw', 'predictions', ['embedding'], unique=False, schema='public', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_predictions_hypothesis_id'), 'predictions', ['hypothesis_id'], unique=False, schema='public')
    op.create_index('ix_predictions_source_hypothesis_ids_gin', 'predictions', ['source_hypothesis_ids'], unique=False, schema='public', postgresql_using='gin')
    op.create_index(op.f('ix_predictions_status'), 'predictions', ['status'], unique=False, schema='public')
    op.create_index(op.f('ix_predictions_workspace_name'), 'predictions', ['workspace_name'], unique=False, schema='public')
    op.create_table('falsification_traces',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('prediction_id', sa.TEXT(), nullable=False),
    sa.Column('search_queries', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('NULL'), nullable=True),
    sa.Column('contradicting_premise_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('NULL'), nullable=True),
    sa.Column('reasoning_chain', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('final_status', sa.TEXT(), server_default='untested', nullable=False),
    sa.Column('search_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('search_efficiency_score', sa.Float(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('workspace_name', sa.TEXT(), nullable=False),
    sa.Column('collection_id', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("final_status IN ('unfalsified', 'falsified', 'untested')", name=op.f('ck_falsification_traces_falsification_trace_status_valid')),
    sa.CheckConstraint("id ~ '^[A-Za-z0-9_-]+$'", name=op.f('ck_falsification_traces_falsification_trace_id_format')),
    sa.CheckConstraint('length(id) = 21', name=op.f('ck_falsification_traces_falsification_trace_id_length')),
    sa.CheckConstraint('search_efficiency_score >= 0.0 AND search_efficiency_score <= 1.0 OR search_efficiency_score IS NULL', name=op.f('ck_falsification_traces_falsification_trace_efficiency_range')),
    sa.ForeignKeyConstraint(['prediction_id'], ['public.predictions.id'], name=op.f('fk_falsification_traces_prediction_id_predictions')),
    sa.ForeignKeyConstraint(['workspace_name'], ['public.workspaces.name'], name=op.f('fk_falsification_traces_workspace_name_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_falsification_traces')),
    schema='public'
    )
    op.create_index(op.f('ix_falsification_traces_collection_id'), 'falsification_traces', ['collection_id'], unique=False, schema='public')
    op.create_index('ix_falsification_traces_contradicting_premise_ids_gin', 'falsification_traces', ['contradicting_premise_ids'], unique=False, schema='public', postgresql_using='gin')
    op.create_index(op.f('ix_falsification_traces_created_at'), 'falsification_traces', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('ix_falsification_traces_final_status'), 'falsification_traces', ['final_status'], unique=False, schema='public')
    op.create_index(op.f('ix_falsification_traces_prediction_id'), 'falsification_traces', ['prediction_id'], unique=False, schema='public')
    op.create_index('ix_falsification_traces_search_queries_gin', 'falsification_traces', ['search_queries'], unique=False, schema='public', postgresql_using='gin')
    op.create_index(op.f('ix_falsification_traces_workspace_name'), 'falsification_traces', ['workspace_name'], unique=False, schema='public')
    op.drop_constraint(op.f('fk_collections_observed_workspace_name_peers'), 'collections', type_='foreignkey')
    op.drop_constraint(op.f('fk_collections_workspace_name_workspaces'), 'collections', type_='foreignkey')
    op.drop_constraint(op.f('fk_collections_observer_workspace_name_peers'), 'collections', type_='foreignkey')
    op.create_foreign_key(op.f('fk_collections_observed_workspace_name_peers'), 'collections', 'peers', ['observed', 'workspace_name'], ['name', 'workspace_name'], source_schema='public', referent_schema='public')
    op.create_foreign_key(op.f('fk_collections_observer_workspace_name_peers'), 'collections', 'peers', ['observer', 'workspace_name'], ['name', 'workspace_name'], source_schema='public', referent_schema='public')
    op.create_foreign_key(op.f('fk_collections_workspace_name_workspaces'), 'collections', 'workspaces', ['workspace_name'], ['name'], source_schema='public', referent_schema='public')
    op.add_column('documents', sa.Column('provenance_type', sa.TEXT(), nullable=True))
    op.add_column('documents', sa.Column('agent_trace_id', sa.TEXT(), nullable=True))
    op.create_index(op.f('ix_documents_agent_trace_id'), 'documents', ['agent_trace_id'], unique=False, schema='public')
    op.create_index(op.f('ix_documents_provenance_type'), 'documents', ['provenance_type'], unique=False, schema='public')
    op.drop_constraint(op.f('fk_documents_observer_observed_workspace_name_collections'), 'documents', type_='foreignkey')
    op.drop_constraint(op.f('fk_documents_session_workspace'), 'documents', type_='foreignkey')
    op.drop_constraint(op.f('fk_documents_workspace_name_workspaces'), 'documents', type_='foreignkey')
    op.drop_constraint(op.f('fk_documents_observer_workspace_name_peers'), 'documents', type_='foreignkey')
    op.drop_constraint(op.f('fk_documents_observed_workspace_name_peers'), 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documents_observer_workspace_name_peers'), 'documents', 'peers', ['observer', 'workspace_name'], ['name', 'workspace_name'], source_schema='public', referent_schema='public')
    op.create_foreign_key(op.f('fk_documents_session_name_workspace_name_sessions'), 'documents', 'sessions', ['session_name', 'workspace_name'], ['name', 'workspace_name'], source_schema='public', referent_schema='public')
    op.create_foreign_key(op.f('fk_documents_observed_workspace_name_peers'), 'documents', 'peers', ['observed', 'workspace_name'], ['name', 'workspace_name'], source_schema='public', referent_schema='public')
    op.create_foreign_key(op.f('fk_documents_observer_observed_workspace_name_collections'), 'documents', 'collections', ['observer', 'observed', 'workspace_name'], ['observer', 'observed', 'workspace_name'], source_schema='public', referent_schema='public')
    op.create_foreign_key(op.f('fk_documents_workspace_name_workspaces'), 'documents', 'workspaces', ['workspace_name'], ['name'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('fk_message_embeddings_session_name_workspace_name_sessions'), 'message_embeddings', type_='foreignkey')
    op.drop_constraint(op.f('fk_message_embeddings_message_id_messages'), 'message_embeddings', type_='foreignkey')
    op.drop_constraint(op.f('fk_message_embeddings_peer_name_workspace_name_peers'), 'message_embeddings', type_='foreignkey')
    op.drop_constraint(op.f('fk_message_embeddings_workspace_name_workspaces'), 'message_embeddings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_message_embeddings_peer_name_workspace_name_peers'), 'message_embeddings', 'peers', ['peer_name', 'workspace_name'], ['name', 'workspace_name'], source_schema='public', referent_schema='public')
    op.create_foreign_key(op.f('fk_message_embeddings_message_id_messages'), 'message_embeddings', 'messages', ['message_id'], ['public_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_message_embeddings_workspace_name_workspaces'), 'message_embeddings', 'workspaces', ['workspace_name'], ['name'], source_schema='public', referent_schema='public')
    op.create_foreign_key(op.f('fk_message_embeddings_session_name_workspace_name_sessions'), 'message_embeddings', 'sessions', ['session_name', 'workspace_name'], ['name', 'workspace_name'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('fk_messages_peer_name_peers'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('fk_messages_session_name_sessions'), 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('fk_messages_peer_name_workspace_name_peers'), 'messages', 'peers', ['peer_name', 'workspace_name'], ['name', 'workspace_name'], source_schema='public', referent_schema='public')
    op.create_foreign_key(op.f('fk_messages_session_name_workspace_name_sessions'), 'messages', 'sessions', ['session_name', 'workspace_name'], ['name', 'workspace_name'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('fk_peers_workspace_name_workspaces'), 'peers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_peers_workspace_name_workspaces'), 'peers', 'workspaces', ['workspace_name'], ['name'], source_schema='public', referent_schema='public')
    op.add_column('queue', sa.Column('depends_on_task_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('NULL'), nullable=True))
    op.drop_constraint(op.f('fk_queue_message_id'), 'queue', type_='foreignkey')
    op.drop_constraint(op.f('fk_queue_session_id'), 'queue', type_='foreignkey')
    op.drop_constraint(op.f('fk_queue_workspace_name'), 'queue', type_='foreignkey')
    op.create_foreign_key(op.f('fk_queue_message_id_messages'), 'queue', 'messages', ['message_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(op.f('fk_queue_session_id_sessions'), 'queue', 'sessions', ['session_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(op.f('fk_queue_workspace_name_workspaces'), 'queue', 'workspaces', ['workspace_name'], ['name'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('fk_session_peers_session_name_workspace_name_sessions'), 'session_peers', type_='foreignkey')
    op.drop_constraint(op.f('fk_session_peers_workspace_name'), 'session_peers', type_='foreignkey')
    op.drop_constraint(op.f('fk_session_peers_peer_name_workspace_name_peers'), 'session_peers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_session_peers_session_name_workspace_name_sessions'), 'session_peers', 'sessions', ['session_name', 'workspace_name'], ['name', 'workspace_name'], source_schema='public', referent_schema='public')
    op.create_foreign_key(op.f('fk_session_peers_workspace_name_workspaces'), 'session_peers', 'workspaces', ['workspace_name'], ['name'], source_schema='public', referent_schema='public')
    op.create_foreign_key(op.f('fk_session_peers_peer_name_workspace_name_peers'), 'session_peers', 'peers', ['peer_name', 'workspace_name'], ['name', 'workspace_name'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('fk_sessions_workspace_name_workspaces'), 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_sessions_workspace_name_workspaces'), 'sessions', 'workspaces', ['workspace_name'], ['name'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('fk_webhook_endpoints_workspace_name_workspaces'), 'webhook_endpoints', type_='foreignkey')
    op.create_foreign_key(op.f('fk_webhook_endpoints_workspace_name_workspaces'), 'webhook_endpoints', 'workspaces', ['workspace_name'], ['name'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_webhook_endpoints_workspace_name_workspaces'), 'webhook_endpoints', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_webhook_endpoints_workspace_name_workspaces'), 'webhook_endpoints', 'workspaces', ['workspace_name'], ['name'])
    op.drop_constraint(op.f('fk_sessions_workspace_name_workspaces'), 'sessions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_sessions_workspace_name_workspaces'), 'sessions', 'workspaces', ['workspace_name'], ['name'])
    op.drop_constraint(op.f('fk_session_peers_peer_name_workspace_name_peers'), 'session_peers', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_session_peers_workspace_name_workspaces'), 'session_peers', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_session_peers_session_name_workspace_name_sessions'), 'session_peers', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_session_peers_peer_name_workspace_name_peers'), 'session_peers', 'peers', ['peer_name', 'workspace_name'], ['name', 'workspace_name'])
    op.create_foreign_key(op.f('fk_session_peers_workspace_name'), 'session_peers', 'workspaces', ['workspace_name'], ['name'])
    op.create_foreign_key(op.f('fk_session_peers_session_name_workspace_name_sessions'), 'session_peers', 'sessions', ['session_name', 'workspace_name'], ['name', 'workspace_name'])
    op.drop_constraint(op.f('fk_queue_workspace_name_workspaces'), 'queue', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_queue_session_id_sessions'), 'queue', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_queue_message_id_messages'), 'queue', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_queue_workspace_name'), 'queue', 'workspaces', ['workspace_name'], ['name'])
    op.create_foreign_key(op.f('fk_queue_session_id'), 'queue', 'sessions', ['session_id'], ['id'])
    op.create_foreign_key(op.f('fk_queue_message_id'), 'queue', 'messages', ['message_id'], ['id'])
    op.drop_column('queue', 'depends_on_task_ids')
    op.drop_constraint(op.f('fk_peers_workspace_name_workspaces'), 'peers', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_peers_workspace_name_workspaces'), 'peers', 'workspaces', ['workspace_name'], ['name'])
    op.drop_constraint(op.f('fk_messages_session_name_workspace_name_sessions'), 'messages', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_messages_peer_name_workspace_name_peers'), 'messages', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_messages_session_name_sessions'), 'messages', 'sessions', ['session_name', 'workspace_name'], ['name', 'workspace_name'])
    op.create_foreign_key(op.f('fk_messages_peer_name_peers'), 'messages', 'peers', ['peer_name', 'workspace_name'], ['name', 'workspace_name'])
    op.drop_constraint(op.f('fk_message_embeddings_session_name_workspace_name_sessions'), 'message_embeddings', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_message_embeddings_workspace_name_workspaces'), 'message_embeddings', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_message_embeddings_message_id_messages'), 'message_embeddings', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_message_embeddings_peer_name_workspace_name_peers'), 'message_embeddings', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_message_embeddings_workspace_name_workspaces'), 'message_embeddings', 'workspaces', ['workspace_name'], ['name'])
    op.create_foreign_key(op.f('fk_message_embeddings_peer_name_workspace_name_peers'), 'message_embeddings', 'peers', ['peer_name', 'workspace_name'], ['name', 'workspace_name'])
    op.create_foreign_key(op.f('fk_message_embeddings_message_id_messages'), 'message_embeddings', 'messages', ['message_id'], ['public_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_message_embeddings_session_name_workspace_name_sessions'), 'message_embeddings', 'sessions', ['session_name', 'workspace_name'], ['name', 'workspace_name'])
    op.drop_constraint(op.f('fk_documents_workspace_name_workspaces'), 'documents', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_documents_observer_observed_workspace_name_collections'), 'documents', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_documents_observed_workspace_name_peers'), 'documents', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_documents_session_name_workspace_name_sessions'), 'documents', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_documents_observer_workspace_name_peers'), 'documents', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documents_observed_workspace_name_peers'), 'documents', 'peers', ['observed', 'workspace_name'], ['name', 'workspace_name'])
    op.create_foreign_key(op.f('fk_documents_observer_workspace_name_peers'), 'documents', 'peers', ['observer', 'workspace_name'], ['name', 'workspace_name'])
    op.create_foreign_key(op.f('fk_documents_workspace_name_workspaces'), 'documents', 'workspaces', ['workspace_name'], ['name'])
    op.create_foreign_key(op.f('fk_documents_session_workspace'), 'documents', 'sessions', ['session_name', 'workspace_name'], ['name', 'workspace_name'])
    op.create_foreign_key(op.f('fk_documents_observer_observed_workspace_name_collections'), 'documents', 'collections', ['observer', 'observed', 'workspace_name'], ['observer', 'observed', 'workspace_name'])
    op.drop_index(op.f('ix_documents_provenance_type'), table_name='documents', schema='public')
    op.drop_index(op.f('ix_documents_agent_trace_id'), table_name='documents', schema='public')
    op.drop_column('documents', 'agent_trace_id')
    op.drop_column('documents', 'provenance_type')
    op.drop_constraint(op.f('fk_collections_workspace_name_workspaces'), 'collections', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_collections_observer_workspace_name_peers'), 'collections', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_collections_observed_workspace_name_peers'), 'collections', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_collections_observer_workspace_name_peers'), 'collections', 'peers', ['observer', 'workspace_name'], ['name', 'workspace_name'])
    op.create_foreign_key(op.f('fk_collections_workspace_name_workspaces'), 'collections', 'workspaces', ['workspace_name'], ['name'])
    op.create_foreign_key(op.f('fk_collections_observed_workspace_name_peers'), 'collections', 'peers', ['observed', 'workspace_name'], ['name', 'workspace_name'])
    op.drop_index(op.f('ix_falsification_traces_workspace_name'), table_name='falsification_traces', schema='public')
    op.drop_index('ix_falsification_traces_search_queries_gin', table_name='falsification_traces', schema='public', postgresql_using='gin')
    op.drop_index(op.f('ix_falsification_traces_prediction_id'), table_name='falsification_traces', schema='public')
    op.drop_index(op.f('ix_falsification_traces_final_status'), table_name='falsification_traces', schema='public')
    op.drop_index(op.f('ix_falsification_traces_created_at'), table_name='falsification_traces', schema='public')
    op.drop_index('ix_falsification_traces_contradicting_premise_ids_gin', table_name='falsification_traces', schema='public', postgresql_using='gin')
    op.drop_index(op.f('ix_falsification_traces_collection_id'), table_name='falsification_traces', schema='public')
    op.drop_table('falsification_traces', schema='public')
    op.drop_index(op.f('ix_predictions_workspace_name'), table_name='predictions', schema='public')
    op.drop_index(op.f('ix_predictions_status'), table_name='predictions', schema='public')
    op.drop_index('ix_predictions_source_hypothesis_ids_gin', table_name='predictions', schema='public', postgresql_using='gin')
    op.drop_index(op.f('ix_predictions_hypothesis_id'), table_name='predictions', schema='public')
    op.drop_index('ix_predictions_embedding_hnsw', table_name='predictions', schema='public', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_predictions_created_at'), table_name='predictions', schema='public')
    op.drop_index(op.f('ix_predictions_collection_id'), table_name='predictions', schema='public')
    op.drop_table('predictions', schema='public')
    op.drop_index(op.f('ix_inductions_workspace_name'), table_name='inductions', schema='public')
    op.drop_index('ix_inductions_source_premise_ids_gin', table_name='inductions', schema='public', postgresql_using='gin')
    op.drop_index('ix_inductions_source_prediction_ids_gin', table_name='inductions', schema='public', postgresql_using='gin')
    op.drop_index(op.f('ix_inductions_pattern_type'), table_name='inductions', schema='public')
    op.drop_index(op.f('ix_inductions_observer'), table_name='inductions', schema='public')
    op.drop_index(op.f('ix_inductions_observed'), table_name='inductions', schema='public')
    op.drop_index(op.f('ix_inductions_created_at'), table_name='inductions', schema='public')
    op.drop_index(op.f('ix_inductions_confidence'), table_name='inductions', schema='public')
    op.drop_index(op.f('ix_inductions_collection_id'), table_name='inductions', schema='public')
    op.drop_table('inductions', schema='public')
    op.drop_index(op.f('ix_hypotheses_workspace_name'), table_name='hypotheses', schema='public')
    op.drop_index(op.f('ix_hypotheses_status'), table_name='hypotheses', schema='public')
    op.drop_index('ix_hypotheses_source_premise_ids_gin', table_name='hypotheses', schema='public', postgresql_using='gin')
    op.drop_index(op.f('ix_hypotheses_observer'), table_name='hypotheses', schema='public')
    op.drop_index(op.f('ix_hypotheses_observed'), table_name='hypotheses', schema='public')
    op.drop_index(op.f('ix_hypotheses_created_at'), table_name='hypotheses', schema='public')
    op.drop_index(op.f('ix_hypotheses_collection_id'), table_name='hypotheses', schema='public')
    op.drop_table('hypotheses', schema='public')
    # ### end Alembic commands ###
