"""add_collection_id_partition_to_documents_table

Revision ID: a5c5965af1a6
Revises: 20f89a421aff
Create Date: 2025-05-16 11:05:03.907208

"""
from os import getenv
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a5c5965af1a6'
down_revision: Union[str, None] = '20f89a421aff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Number of hash partitions to create
NUM_PARTITIONS = 10

def upgrade() -> None:
    schema = getenv("DATABASE_SCHEMA", "public")

    # 1. Create documents_temp table with minimal constraints
    op.execute(f"""
    CREATE TABLE {schema}.documents_temp (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
        collection_id TEXT NOT NULL,
        public_id TEXT NOT NULL,
        metadata JSONB NOT NULL DEFAULT '{{}}',
        content TEXT NOT NULL,
        embedding vector(1536),
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        user_id TEXT NOT NULL,
        app_id TEXT NOT NULL,

        CONSTRAINT pk_documents_temp PRIMARY KEY (collection_id, id),
        CONSTRAINT fk_documents_temp_collection_id_collections 
            FOREIGN KEY (collection_id) REFERENCES {schema}.collections(public_id),

        CONSTRAINT fk_documents_temp_user_id_users 
            FOREIGN KEY (user_id) REFERENCES {schema}.users(public_id),

        CONSTRAINT fk_documents_temp_app_id_apps 
            FOREIGN KEY (app_id) REFERENCES {schema}.apps(public_id),

        CONSTRAINT public_id_length CHECK (length(public_id) = 21),
        CONSTRAINT content_length CHECK (length(content) <= 65535),
        CONSTRAINT public_id_format CHECK (public_id ~ '^[A-Za-z0-9_-]+$')
    ) PARTITION BY HASH (collection_id);
    """)

    # 2. Create hash partitions
    op.execute(
        f"""
        DO $$
        DECLARE
            i INT;
        BEGIN
            FOR i IN 0..{NUM_PARTITIONS-1} LOOP
                EXECUTE
                    'CREATE TABLE '  || quote_ident('{schema}') || '.' ||
                    quote_ident('documents_temp_'||i) ||
                    ' PARTITION OF ' || quote_ident('{schema}') || '.documents_temp
                      FOR VALUES WITH (MODULUS {NUM_PARTITIONS}, REMAINDER '|| i || ')';
            END LOOP;
        END$$;
        """
    )

    # 3. Create indexes
    op.execute(f"""
    CREATE UNIQUE INDEX uq_documents_temp_collection_public_id ON {schema}.documents_temp (collection_id, public_id);
    CREATE INDEX ix_documents_temp_created_at ON {schema}.documents_temp (created_at);
    CREATE INDEX ix_documents_temp_user_id ON {schema}.documents_temp (user_id);
    CREATE INDEX ix_documents_temp_app_id ON {schema}.documents_temp (app_id);
    """)

    # 4. Bulk-copy data from our existing documents table
    op.execute(
        f"""
        INSERT INTO {schema}.documents_temp (
            id, collection_id, public_id, metadata, content,
            embedding, created_at, user_id, app_id
        ) OVERRIDING SYSTEM VALUE
        SELECT
            id, collection_id, public_id, metadata, content,
            embedding, created_at, user_id, app_id
        FROM public.documents;
        """
    )

    # 5. Rename the previous constraints and indexes
    op.execute(
        f"""
        DO $$
        DECLARE
            rec RECORD;
        BEGIN
            -- rename indexes
            FOR rec IN
                SELECT indexname
                  FROM pg_indexes
                 WHERE schemaname = '{schema}'
                   AND tablename  = 'documents'
            LOOP
                EXECUTE
                  'ALTER INDEX ' || quote_ident('{schema}') || '.' ||
                  quote_ident(rec.indexname) ||
                  ' RENAME TO '   || quote_ident(rec.indexname || '_old');
            END LOOP;

            -- rename constraints
            FOR rec IN
                SELECT conname
                  FROM pg_constraint c
                  JOIN pg_class  t ON c.conrelid = t.oid
                  JOIN pg_namespace n ON t.relnamespace = n.oid
                 WHERE n.nspname = '{schema}'
                   AND t.relname = 'documents'
            LOOP
                EXECUTE
                  'ALTER TABLE ' || quote_ident('{schema}') || '.documents
                     RENAME CONSTRAINT ' || quote_ident(rec.conname) ||
                  ' TO ' || quote_ident(rec.conname || '_old');
            END LOOP;
        END$$;
        """
    )

    # 6. Swap the tables
    op.execute(f'ALTER TABLE {schema}.documents RENAME TO documents_old;')
    op.execute(f'ALTER TABLE {schema}.documents_temp RENAME TO documents;')

    # 8. Rename the partitions to match the new table name
    op.execute(
        f"""
        DO $$
        DECLARE i INT;
        BEGIN
            FOR i IN 0..{NUM_PARTITIONS-1} LOOP
                EXECUTE
                  'ALTER TABLE ' || quote_ident('{schema}') || '.documents_temp_'||i||
                  ' RENAME TO documents_' || i;            
            END LOOP;
        END$$;
        """
    )

    # 9. Rename constraints and indexes to match the new table name
    op.execute(f"""
    -- Rename Primary Key constraint
    -- ALTER TABLE {schema}.documents RENAME CONSTRAINT pk_documents_temp TO pk_documents;
    
    -- Rename Foreign Key constraints
    ALTER TABLE {schema}.documents RENAME CONSTRAINT fk_documents_temp_collection_id_collections TO fk_documents_collection_id_collections;
    ALTER TABLE {schema}.documents RENAME CONSTRAINT fk_documents_temp_user_id_users TO fk_documents_user_id_users;
    ALTER TABLE {schema}.documents RENAME CONSTRAINT fk_documents_temp_app_id_apps TO fk_documents_app_id_apps;
    
    -- Rename Indexes
    ALTER INDEX {schema}.uq_documents_temp_collection_public_id RENAME TO uq_documents_collection_public_id;
    ALTER INDEX {schema}.ix_documents_temp_created_at RENAME TO ix_documents_created_at;
    ALTER INDEX {schema}.ix_documents_temp_user_id RENAME TO ix_documents_user_id;
    ALTER INDEX {schema}.ix_documents_temp_app_id RENAME TO ix_documents_app_id;
    """)

def downgrade() -> None:
    schema = getenv("DATABASE_SCHEMA", "public")

    # 1. Move partitioned table aside as documents_new
    op.execute(f'ALTER TABLE {schema}.documents RENAME TO documents_new;')

    # 2. also rename its partitions so we can drop them safely later
    op.execute(
        f"""
        DO $$
        DECLARE i INT;
        BEGIN
            FOR i IN 0..{NUM_PARTITIONS-1} LOOP
                EXECUTE
                  'ALTER TABLE ' || quote_ident('{schema}') || '.documents_'||i||
                  ' RENAME TO documents_new_'||i;
            END LOOP;
        END$$;
        """
    )

    # 3. Put the old table back in place and restore names
    op.execute(f'ALTER TABLE {schema}.documents_old RENAME TO documents;')

    # 4. copy any rows written *after* the upgrade back into the legacy
    op.execute(
        f"""
        INSERT INTO {schema}.documents AS d (
            id, collection_id, public_id, metadata, content,
            embedding, created_at, user_id, app_id
        )
        SELECT
            id, collection_id, public_id, metadata, content,
            embedding, created_at, user_id, app_id
        FROM {schema}.documents_new
        ON CONFLICT (id) DO NOTHING;    -- skip rows that were already there
        """
    )

    # 5. drop the partitioned table
    op.execute(f'DROP TABLE IF EXISTS {schema}.documents_new CASCADE;')

    # 6. Restore old index names and constraints
    op.execute(
        f"""
        DO $$
        DECLARE rec RECORD;
        BEGIN
            -- restore old index names
            FOR rec IN
                SELECT indexname
                  FROM pg_indexes
                 WHERE schemaname = '{schema}'
                   AND tablename  = 'documents'
                   AND indexname LIKE '%_old'
            LOOP
                EXECUTE
                  'ALTER INDEX ' || quote_ident('{schema}') || '.' ||
                  quote_ident(rec.indexname) ||
                  ' RENAME TO '  ||
                  quote_ident(left(rec.indexname, length(rec.indexname)-4));
            END LOOP;

            -- restore old constraint names
            FOR rec IN
                SELECT conname
                  FROM pg_constraint c
                  JOIN pg_class  t ON c.conrelid = t.oid
                  JOIN pg_namespace n ON t.relnamespace = n.oid
                 WHERE n.nspname = '{schema}'
                   AND t.relname  = 'documents'
                   AND conname LIKE '%_old'
            LOOP
                EXECUTE
                  'ALTER TABLE ' || quote_ident('{schema}') || '.documents
                     RENAME CONSTRAINT ' || quote_ident(rec.conname) ||
                  ' TO ' || quote_ident(left(rec.conname, length(rec.conname)-4));
            END LOOP;
        END$$;
        """
    )
