"""standardize_constraint_names

Revision ID: baa22cad81e2
Revises: b8183c5ffb48
Create Date: 2025-11-15 01:16:40.937103

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.utils import get_schema

# revision identifiers, used by Alembic.
revision: str = "baa22cad81e2"
down_revision: str | None = "b8183c5ffb48"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

schema = get_schema()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("unique_work_unit_key"),
        "active_queue_sessions",
        schema=schema,
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("uq_active_queue_sessions_work_unit_key"),
        "active_queue_sessions",
        ["work_unit_key"],
        schema=schema,
    )
    # Drop FK from documents to collections first (depends on unique constraint)
    op.drop_constraint(
        op.f("fk_documents_observer_observed_workspace_name_collections"),
        "documents",
        schema=schema,
        type_="foreignkey",
    )
    op.drop_index(
        op.f("idx_collections_observed"), table_name="collections", schema=schema
    )
    op.drop_index(
        op.f("idx_collections_observer"), table_name="collections", schema=schema
    )
    op.drop_index(
        op.f("ix_collections_created_at"), table_name="collections", schema=schema
    )
    op.drop_index(
        op.f("ix_collections_workspace_name"), table_name="collections", schema=schema
    )
    op.drop_constraint(
        op.f("unique_observer_observed_collection"),
        "collections",
        schema=schema,
        type_="unique",
    )
    op.create_index(
        op.f("ix_collections_created_at"),
        "collections",
        ["created_at"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_collections_observed"),
        "collections",
        ["observed"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_collections_observer"),
        "collections",
        ["observer"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_collections_workspace_name"),
        "collections",
        ["workspace_name"],
        unique=False,
        schema=schema,
    )
    op.create_unique_constraint(
        op.f("uq_collections_observer_observed_workspace_name"),
        "collections",
        ["observer", "observed", "workspace_name"],
        schema=schema,
    )
    # Recreate FK from documents to collections (let naming convention generate name)
    op.create_foreign_key(
        None,
        "documents",
        "collections",
        ["observer", "observed", "workspace_name"],
        ["observer", "observed", "workspace_name"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.drop_index(
        op.f("idx_documents_embedding_hnsw"),
        table_name="documents",
        schema=schema,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.drop_index(op.f("idx_documents_observed"), table_name="documents", schema=schema)
    op.drop_index(op.f("idx_documents_observer"), table_name="documents", schema=schema)
    op.drop_index(
        op.f("idx_documents_session_name"), table_name="documents", schema=schema
    )
    op.drop_index(
        op.f("ix_documents_created_at"), table_name="documents", schema=schema
    )
    op.drop_index(
        op.f("ix_documents_workspace_name"), table_name="documents", schema=schema
    )
    op.create_index(
        "ix_documents_embedding_hnsw",
        "documents",
        ["embedding"],
        unique=False,
        schema=schema,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_documents_created_at"),
        "documents",
        ["created_at"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_documents_observed"),
        "documents",
        ["observed"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_documents_observer"),
        "documents",
        ["observer"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_documents_session_name"),
        "documents",
        ["session_name"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_documents_workspace_name"),
        "documents",
        ["workspace_name"],
        unique=False,
        schema=schema,
    )
    op.drop_index(
        op.f("idx_message_embeddings_created_at"),
        table_name="message_embeddings",
        schema=schema,
    )
    op.drop_index(
        op.f("idx_message_embeddings_embedding_hnsw"),
        table_name="message_embeddings",
        schema=schema,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.drop_index(
        op.f("idx_message_embeddings_message_id"),
        table_name="message_embeddings",
        schema=schema,
    )
    op.drop_index(
        op.f("idx_message_embeddings_peer_name"),
        table_name="message_embeddings",
        schema=schema,
    )
    op.drop_index(
        op.f("idx_message_embeddings_session_name"),
        table_name="message_embeddings",
        schema=schema,
    )
    op.drop_index(
        op.f("idx_message_embeddings_workspace_name"),
        table_name="message_embeddings",
        schema=schema,
    )
    op.create_index(
        "ix_message_embeddings_embedding_hnsw",
        "message_embeddings",
        ["embedding"],
        unique=False,
        schema=schema,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_message_embeddings_created_at"),
        "message_embeddings",
        ["created_at"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_message_embeddings_message_id"),
        "message_embeddings",
        ["message_id"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_message_embeddings_peer_name"),
        "message_embeddings",
        ["peer_name"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_message_embeddings_session_name"),
        "message_embeddings",
        ["session_name"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_message_embeddings_workspace_name"),
        "message_embeddings",
        ["workspace_name"],
        unique=False,
        schema=schema,
    )
    op.drop_constraint(
        op.f("message_embeddings_message_id_fkey"),
        "message_embeddings",
        schema=schema,
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_message_embeddings_message_id_messages"),
        "message_embeddings",
        "messages",
        ["message_id"],
        ["public_id"],
        source_schema=schema,
        referent_schema=schema,
        ondelete="CASCADE",
    )
    op.drop_index(
        op.f("idx_messages_content_gin"),
        table_name="messages",
        schema=schema,
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("idx_messages_session_lookup"),
        table_name="messages",
        schema=schema,
        postgresql_include=["id", "created_at"],
    )
    op.drop_index(op.f("ix_messages_created_at"), table_name="messages", schema=schema)
    op.drop_index(op.f("ix_messages_id"), table_name="messages", schema=schema)
    op.drop_index(op.f("ix_messages_peer_name"), table_name="messages", schema=schema)
    op.drop_index(op.f("ix_messages_public_id"), table_name="messages", schema=schema)
    op.drop_index(
        op.f("ix_messages_workspace_name"), table_name="messages", schema=schema
    )
    op.drop_constraint(
        op.f("uq_messages_session_seq"), "messages", schema=schema, type_="unique"
    )
    op.create_index(
        "ix_messages_content_gin",
        "messages",
        [sa.literal_column("to_tsvector('english', content)")],
        unique=False,
        schema=schema,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_messages_session_lookup",
        "messages",
        ["session_name", "id"],
        unique=False,
        schema=schema,
        postgresql_include=["id", "created_at"],
    )
    op.create_index(
        op.f("ix_messages_created_at"),
        "messages",
        ["created_at"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_messages_peer_name"),
        "messages",
        ["peer_name"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_messages_workspace_name"),
        "messages",
        ["workspace_name"],
        unique=False,
        schema=schema,
    )
    op.create_unique_constraint(
        op.f("uq_messages_workspace_name_session_name_seq_in_session"),
        "messages",
        ["workspace_name", "session_name", "seq_in_session"],
        schema=schema,
    )
    op.drop_constraint(
        op.f("fk_messages_workspace_name_workspaces"),
        "messages",
        schema=schema,
        type_="foreignkey",
    )
    op.drop_index(op.f("idx_peers_workspace_lookup"), table_name="peers", schema=schema)
    op.drop_index(op.f("ix_peers_created_at"), table_name="peers", schema=schema)
    op.drop_index(op.f("ix_peers_name"), table_name="peers", schema=schema)
    op.drop_index(op.f("ix_peers_workspace_name"), table_name="peers", schema=schema)
    op.drop_constraint(
        op.f("unique_name_workspace_peer"), "peers", schema=schema, type_="unique"
    )
    op.create_index(
        op.f("ix_peers_created_at"),
        "peers",
        ["created_at"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_peers_workspace_name"),
        "peers",
        ["workspace_name"],
        unique=False,
        schema=schema,
    )
    op.create_unique_constraint(
        op.f("uq_peers_name_workspace_name"),
        "peers",
        ["name", "workspace_name"],
        schema=schema,
    )
    op.drop_index(op.f("ix_queue_created_at"), table_name="queue", schema=schema)
    op.drop_index(op.f("ix_queue_session_id"), table_name="queue", schema=schema)
    op.drop_index(
        op.f("ix_queue_work_unit_key_processed_id"), table_name="queue", schema=schema
    )
    op.drop_index(op.f("ix_queue_workspace_name"), table_name="queue", schema=schema)
    op.drop_index(
        op.f("ix_queue_workspace_name_processed"), table_name="queue", schema=schema
    )
    op.create_index(
        op.f("ix_queue_created_at"),
        "queue",
        ["created_at"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_queue_processed"),
        "queue",
        ["processed"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_queue_session_id"),
        "queue",
        ["session_id"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_queue_workspace_name"),
        "queue",
        ["workspace_name"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        "work_unit_key", "queue", ["processed", "id"], unique=False, schema=schema
    )
    op.drop_index(op.f("ix_sessions_created_at"), table_name="sessions", schema=schema)
    op.drop_constraint(
        op.f("unique_session_name"), "sessions", schema=schema, type_="unique"
    )
    op.create_index(
        op.f("ix_sessions_created_at"),
        "sessions",
        ["created_at"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_sessions_workspace_name"),
        "sessions",
        ["workspace_name"],
        unique=False,
        schema=schema,
    )
    op.create_unique_constraint(
        op.f("uq_sessions_name_workspace_name"),
        "sessions",
        ["name", "workspace_name"],
        schema=schema,
    )
    op.drop_index(
        op.f("idx_webhook_endpoints_workspace_lookup"),
        table_name="webhook_endpoints",
        schema=schema,
    )
    op.create_index(
        op.f("ix_webhook_endpoints_workspace_name"),
        "webhook_endpoints",
        ["workspace_name"],
        unique=False,
        schema=schema,
    )
    op.drop_index(
        op.f("ix_workspaces_created_at"), table_name="workspaces", schema=schema
    )
    op.drop_index(op.f("ix_workspaces_name"), table_name="workspaces", schema=schema)
    op.drop_constraint(
        op.f("uq_apps_name"), "workspaces", schema=schema, type_="unique"
    )
    op.create_index(
        op.f("ix_workspaces_created_at"),
        "workspaces",
        ["created_at"],
        unique=False,
        schema=schema,
    )
    op.create_unique_constraint(
        op.f("uq_workspaces_name"), "workspaces", ["name"], schema=schema
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_workspaces_name"), "workspaces", schema=schema, type_="unique"
    )
    op.drop_index(
        op.f("ix_workspaces_created_at"), table_name="workspaces", schema=schema
    )
    op.create_unique_constraint(
        op.f("uq_apps_name"),
        "workspaces",
        ["name"],
        schema=schema,
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_workspaces_name"), "workspaces", ["name"], unique=False, schema=schema
    )
    op.create_index(
        op.f("ix_workspaces_created_at"),
        "workspaces",
        ["created_at"],
        unique=False,
        schema=schema,
    )
    op.drop_index(
        op.f("ix_webhook_endpoints_workspace_name"),
        table_name="webhook_endpoints",
        schema=schema,
    )
    op.create_index(
        op.f("idx_webhook_endpoints_workspace_lookup"),
        "webhook_endpoints",
        ["workspace_name"],
        unique=False,
        schema=schema,
    )
    op.drop_constraint(
        op.f("uq_sessions_name_workspace_name"),
        "sessions",
        schema=schema,
        type_="unique",
    )
    op.drop_index(
        op.f("ix_sessions_workspace_name"), table_name="sessions", schema=schema
    )
    op.drop_index(op.f("ix_sessions_created_at"), table_name="sessions", schema=schema)
    op.create_unique_constraint(
        op.f("unique_session_name"),
        "sessions",
        ["name", "workspace_name"],
        schema=schema,
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_sessions_created_at"),
        "sessions",
        ["created_at"],
        unique=False,
        schema=schema,
    )
    op.drop_index("work_unit_key", table_name="queue", schema=schema)
    op.drop_index(op.f("ix_queue_workspace_name"), table_name="queue", schema=schema)
    op.drop_index(op.f("ix_queue_session_id"), table_name="queue", schema=schema)
    op.drop_index(op.f("ix_queue_processed"), table_name="queue", schema=schema)
    op.drop_index(op.f("ix_queue_created_at"), table_name="queue", schema=schema)
    op.create_index(
        op.f("ix_queue_workspace_name_processed"),
        "queue",
        ["workspace_name", "processed"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_queue_workspace_name"),
        "queue",
        ["workspace_name"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_queue_work_unit_key_processed_id"),
        "queue",
        ["work_unit_key", "processed", "id"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_queue_session_id"),
        "queue",
        ["session_id"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_queue_created_at"),
        "queue",
        ["created_at"],
        unique=False,
        schema=schema,
    )
    op.drop_constraint(
        op.f("uq_peers_name_workspace_name"), "peers", schema=schema, type_="unique"
    )
    op.drop_index(op.f("ix_peers_workspace_name"), table_name="peers", schema=schema)
    op.drop_index(op.f("ix_peers_created_at"), table_name="peers", schema=schema)
    op.create_unique_constraint(
        op.f("unique_name_workspace_peer"),
        "peers",
        ["name", "workspace_name"],
        schema=schema,
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_peers_workspace_name"),
        "peers",
        ["workspace_name"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_peers_name"), "peers", ["name"], unique=False, schema=schema
    )
    op.create_index(
        op.f("ix_peers_created_at"),
        "peers",
        ["created_at"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("idx_peers_workspace_lookup"),
        "peers",
        ["workspace_name", "name"],
        unique=False,
        schema=schema,
    )
    op.create_foreign_key(
        op.f("fk_messages_workspace_name_workspaces"),
        "messages",
        "workspaces",
        ["workspace_name"],
        ["name"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.drop_constraint(
        op.f("uq_messages_workspace_name_session_name_seq_in_session"),
        "messages",
        schema=schema,
        type_="unique",
    )
    op.drop_index(
        op.f("ix_messages_workspace_name"), table_name="messages", schema=schema
    )
    op.drop_index(op.f("ix_messages_peer_name"), table_name="messages", schema=schema)
    op.drop_index(op.f("ix_messages_created_at"), table_name="messages", schema=schema)
    op.drop_index(
        "ix_messages_session_lookup",
        table_name="messages",
        schema=schema,
        postgresql_include=["id", "created_at"],
    )
    op.drop_index(
        "ix_messages_content_gin",
        table_name="messages",
        schema=schema,
        postgresql_using="gin",
    )
    op.create_unique_constraint(
        op.f("uq_messages_session_seq"),
        "messages",
        ["workspace_name", "session_name", "seq_in_session"],
        schema=schema,
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_messages_workspace_name"),
        "messages",
        ["workspace_name"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_messages_public_id"),
        "messages",
        ["public_id"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_messages_peer_name"),
        "messages",
        ["peer_name"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_messages_id"), "messages", ["id"], unique=False, schema=schema
    )
    op.create_index(
        op.f("ix_messages_created_at"),
        "messages",
        ["created_at"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("idx_messages_session_lookup"),
        "messages",
        ["session_name", "id"],
        unique=False,
        schema=schema,
        postgresql_include=["id", "created_at"],
    )
    op.create_index(
        op.f("idx_messages_content_gin"),
        "messages",
        [sa.literal_column("to_tsvector('english'::regconfig, content)")],
        unique=False,
        schema=schema,
        postgresql_using="gin",
    )
    op.drop_constraint(
        op.f("fk_message_embeddings_message_id_messages"),
        "message_embeddings",
        schema=schema,
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("message_embeddings_message_id_fkey"),
        "message_embeddings",
        "messages",
        ["message_id"],
        ["public_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.drop_index(
        op.f("ix_message_embeddings_workspace_name"),
        table_name="message_embeddings",
        schema=schema,
    )
    op.drop_index(
        op.f("ix_message_embeddings_session_name"),
        table_name="message_embeddings",
        schema=schema,
    )
    op.drop_index(
        op.f("ix_message_embeddings_peer_name"),
        table_name="message_embeddings",
        schema=schema,
    )
    op.drop_index(
        op.f("ix_message_embeddings_message_id"),
        table_name="message_embeddings",
        schema=schema,
    )
    op.drop_index(
        op.f("ix_message_embeddings_created_at"),
        table_name="message_embeddings",
        schema=schema,
    )
    op.drop_index(
        "ix_message_embeddings_embedding_hnsw",
        table_name="message_embeddings",
        schema=schema,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("idx_message_embeddings_workspace_name"),
        "message_embeddings",
        ["workspace_name"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("idx_message_embeddings_session_name"),
        "message_embeddings",
        ["session_name"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("idx_message_embeddings_peer_name"),
        "message_embeddings",
        ["peer_name"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("idx_message_embeddings_message_id"),
        "message_embeddings",
        ["message_id"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("idx_message_embeddings_embedding_hnsw"),
        "message_embeddings",
        ["embedding"],
        unique=False,
        schema=schema,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.create_index(
        op.f("idx_message_embeddings_created_at"),
        "message_embeddings",
        ["created_at"],
        unique=False,
        schema=schema,
    )
    op.drop_index(
        op.f("ix_documents_workspace_name"), table_name="documents", schema=schema
    )
    op.drop_index(
        op.f("ix_documents_session_name"), table_name="documents", schema=schema
    )
    op.drop_index(op.f("ix_documents_observer"), table_name="documents", schema=schema)
    op.drop_index(op.f("ix_documents_observed"), table_name="documents", schema=schema)
    op.drop_index(
        op.f("ix_documents_created_at"), table_name="documents", schema=schema
    )
    op.drop_index(
        "ix_documents_embedding_hnsw",
        table_name="documents",
        schema=schema,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_documents_workspace_name"),
        "documents",
        ["workspace_name"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_documents_created_at"),
        "documents",
        ["created_at"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("idx_documents_session_name"),
        "documents",
        ["session_name"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("idx_documents_observer"),
        "documents",
        ["observer"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("idx_documents_observed"),
        "documents",
        ["observed"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("idx_documents_embedding_hnsw"),
        "documents",
        ["embedding"],
        unique=False,
        schema=schema,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    # Drop FK from documents to collections first (depends on unique constraint)
    op.drop_constraint(
        op.f("fk_documents_observer_observed_workspace_name_collections"),
        "documents",
        schema=schema,
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("uq_collections_observer_observed_workspace_name"),
        "collections",
        schema=schema,
        type_="unique",
    )
    op.drop_index(
        op.f("ix_collections_workspace_name"),
        table_name="collections",
        schema=schema,
    )
    op.drop_index(
        op.f("ix_collections_observer"), table_name="collections", schema=schema
    )
    op.drop_index(
        op.f("ix_collections_observed"), table_name="collections", schema=schema
    )
    op.drop_index(
        op.f("ix_collections_created_at"), table_name="collections", schema=schema
    )
    op.create_unique_constraint(
        op.f("unique_observer_observed_collection"),
        "collections",
        ["observer", "observed", "workspace_name"],
        schema=schema,
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_collections_workspace_name"),
        "collections",
        ["workspace_name"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_collections_created_at"),
        "collections",
        ["created_at"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("idx_collections_observer"),
        "collections",
        ["observer"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("idx_collections_observed"),
        "collections",
        ["observed"],
        unique=False,
        schema=schema,
    )
    # Recreate FK from documents to collections with old name
    op.create_foreign_key(
        op.f("fk_documents_observer_observed_workspace_name_collections"),
        "documents",
        "collections",
        ["observer", "observed", "workspace_name"],
        ["observer", "observed", "workspace_name"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.drop_constraint(
        op.f("uq_active_queue_sessions_work_unit_key"),
        "active_queue_sessions",
        schema=schema,
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("unique_work_unit_key"),
        "active_queue_sessions",
        ["work_unit_key"],
        schema=schema,
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
