services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity
    
    network_mode: service:database
  
  database:
    image: pgvector/pgvector:pg15
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=honcho
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d honcho"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  postgres_data: