//! Parity tests: Rust `SessionContext::to_openai` / `to_anthropic` must match Python SDK output.
//!
//! Fixtures generated by `_generate.py` using the `honcho` Python SDK.
//! Run `cd sdks/python && uv run python -c "import importlib.util as u; s=u.spec_from_file_location('g','../rust/tests/fixtures/parity/_generate.py'); m=u.module_from_spec(s); s.loader.exec_module(m); m.main()"` to regenerate.

#![allow(clippy::unwrap_used, clippy::expect_used, missing_docs)]

use std::fs;
use std::path::PathBuf;

use honcho_ai::types::session::SessionContext;
use pretty_assertions::assert_eq;

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/parity")
}

fn load_scenario(
    name: &str,
) -> (
    SessionContext,
    Vec<serde_json::Value>,
    Vec<serde_json::Value>,
) {
    let base = fixtures_dir().join(name);
    let ctx: SessionContext =
        serde_json::from_str(&fs::read_to_string(base.join("session_context.json")).unwrap())
            .unwrap();
    let openai: Vec<serde_json::Value> =
        serde_json::from_str(&fs::read_to_string(base.join("openai.json")).unwrap()).unwrap();
    let anthropic: Vec<serde_json::Value> =
        serde_json::from_str(&fs::read_to_string(base.join("anthropic.json")).unwrap()).unwrap();
    (ctx, openai, anthropic)
}

fn normalize_peer_card(val: &mut serde_json::Value) {
    let content = match val.get("content").and_then(|c| c.as_str()) {
        Some(c) => c.to_string(),
        None => return,
    };

    if let Some(inner) = content
        .strip_prefix("<peer_card>")
        .and_then(|s| s.strip_suffix("</peer_card>"))
    {
        if let Ok(parsed) = serde_json::from_str::<Vec<String>>(inner) {
            val["content"] = serde_json::Value::String(format!(
                "<peer_card>{}</peer_card>",
                serde_json::to_string(&parsed).expect("re-serializing parsed JSON should not fail")
            ));
        } else {
            let fixed = inner.replace('\'', "\"");
            if let Ok(parsed) = serde_json::from_str::<Vec<String>>(&fixed) {
                val["content"] = serde_json::Value::String(format!(
                    "<peer_card>{}</peer_card>",
                    serde_json::to_string(&parsed)
                        .expect("re-serializing parsed JSON should not fail")
                ));
            }
        }
    }
}

fn normalize_expected(messages: &mut [serde_json::Value]) {
    for msg in messages.iter_mut() {
        normalize_peer_card(msg);
    }
}

#[test]
fn parity_small_openai() {
    let (ctx, expected, _) = load_scenario("small");
    let mut actual = ctx.to_openai("assistant");
    let mut exp = expected;
    normalize_expected(&mut exp);
    normalize_expected(&mut actual);
    assert_eq!(actual, exp);
}

#[test]
fn parity_small_anthropic() {
    let (ctx, _, expected) = load_scenario("small");
    let mut actual = ctx.to_anthropic("assistant");
    let mut exp = expected;
    normalize_expected(&mut exp);
    normalize_expected(&mut actual);
    assert_eq!(actual, exp);
}

#[test]
fn parity_multi_peer_openai() {
    let (ctx, expected, _) = load_scenario("multi_peer");
    let mut actual = ctx.to_openai("bot");
    let mut exp = expected;
    normalize_expected(&mut exp);
    normalize_expected(&mut actual);
    assert_eq!(actual, exp);
}

#[test]
fn parity_multi_peer_anthropic() {
    let (ctx, _, expected) = load_scenario("multi_peer");
    let mut actual = ctx.to_anthropic("bot");
    let mut exp = expected;
    normalize_expected(&mut exp);
    normalize_expected(&mut actual);
    assert_eq!(actual, exp);
}

#[test]
fn parity_with_summary_openai() {
    let (ctx, expected, _) = load_scenario("with_summary");
    let mut actual = ctx.to_openai("assistant");
    let mut exp = expected;
    normalize_expected(&mut exp);
    normalize_expected(&mut actual);
    assert_eq!(actual, exp);
}

#[test]
fn parity_with_summary_anthropic() {
    let (ctx, _, expected) = load_scenario("with_summary");
    let mut actual = ctx.to_anthropic("assistant");
    let mut exp = expected;
    normalize_expected(&mut exp);
    normalize_expected(&mut actual);
    assert_eq!(actual, exp);
}
