# fly.toml app configuration file generated for honcho-restless-dew-484 on 2024-01-18T08:20:57-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "honcho"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]

[processes]
  api = "python -m uvicorn src.main:app --host 0.0.0.0 --port 8000"
  deriver = "python -m src.harvester"

[[services]]
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["deriver"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 250
    soft_limit = 200

[http_service]
  internal_port = 8000
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["api"]
  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
  processes = ["api", "deriver"]
