# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy (Test Environment)
permissions:
  contents: read
on:
  push:
    tags:
      - v*

jobs:
  deploy-honcho-image:
    name: Deploy Honcho Image (Test Environment)
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@1.5
      - run: flyctl deploy --remote-only --build-only --push --no-cache --image-label "deployment-${{ github.ref_name }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  prompt-service:
    name: Push to Service (Test Environment)
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          TAG=${GITHUB_REF_NAME#v}
          IMAGE_LABEL="honcho-image:deployment-${GITHUB_REF_NAME}"
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.TEST_ENV_WEBHOOK_SECRET }}" \
            -d "{\"version\":\"$TAG\",\"image_label\":\"$IMAGE_LABEL\"}" \
            "${{ secrets.TEST_ENV_URL }}/webhooks/v1/add_honcho_version"
